### ISSUE TITLE
Libretro Core (0.9.7) doesn't create save file for Famicom Wars (possibly other games?)

### ISSUE THREAD

**Issue by TopHatHipster** [SourMesen/Mesen#560] opened 2019-01-05 15:41 UTC
As a patched version of Famicom Wars with the English fan translation isn't recognized by RetroArch, I put it in a custom playlist to enjoy the game through the Mesen core. 

Yet, as I try to save the game, shut it off and bootup the game at a later point: there is no save file. Checking the saves folder shows no save file being made despite the game is supposed to save as it is a battery-based game.

I currently use save states to track progress (which also apparently mangles the sound? The only 'fix' would be shutting off the game and booting it up again which stops the purpose of using save states) which is of course a little tedious.

**Comment by SourMesen** [comment] 2019-01-05 21:57
As far as I can tell, this is working properly.

The rom you are using most likely does not set the "Battery" flag properly in its header, so Mesen creates no save file for it (which is normal).  You will either want to find an updated ROM that properly sets the battery flag, or edit the ROM yourself to set it (there are a lot of utilities/programs that will allow you to edit the header settings for .nes files, including the standalone build of Mesen)

I also couldn't reproduce any sound-related problem with save states, as far as I can tell, so I'm unsure what the problem might be (e.g is it Retroarch itself or the Mesen core that is causing a problem, etc.)

Hope that helps!

**Comment by TopHatHipster** [comment] 2019-01-05 23:06
> As far as I can tell, this is working properly.
> 
> The rom you are using most likely does not set the "Battery" flag properly in its header, so Mesen creates no save file for it (which is normal). You will either want to find an updated ROM that properly sets the battery flag, or edit the ROM yourself to set it (there are a lot of utilities/programs that will allow you to edit the header settings for .nes files, including the standalone build of Mesen)
> 
> I also couldn't reproduce any sound-related problem with save states, as far as I can tell, so I'm unsure what the problem might be (e.g is it Retroarch itself or the Mesen core that is causing a problem, etc.)
> 
> Hope that helps!

Ah yes, it was the ROM for some reason! I thought the header was all correct, apparently not. Thank you for pointing out the problem! Now the game does properly save. 

I reproduced the save state audio issue multiple times myself. If I had any additional information, I would've liked to provide it to you to pinpoint the issue.

**Comment by SourMesen** [comment] 2019-01-21 15:13
I've tried reproducing sound issues in a number of games by loading various save states, and the sound always appears to resume properly.  Closing this for now, but if you still have issues with the latest Mesen core & latest version of RetroArch, let me know.

**Closed by SourMesen** 2019-01-21 15:13 UTC
Labels: cannot reproduce, libretro
