### ISSUE TITLE
NESMaker: Incorrect mirroring in 0.9.8

### ISSUE THREAD

**Issue by Taledar** [SourMesen/Mesen#634] opened 2019-06-24 17:09 UTC
Updated Mesen today and tried running the test game that I'm learning with in NESMaker.

It was working fine yesterday with 0.9.7 but something is going on with 0.9.8 causing the right half of the adjacent screen to display and for some tiles to display incorrectly.

![image](https://user-images.githubusercontent.com/18320680/60037703-48086200-9680-11e9-9823-f02ac1aab739.png)

The 0.9.7 image on the right is how it should look.

**Comment by SourMesen** [comment] 2019-06-24 19:22
What kind of mirroring are you using?
The definition of how the iNES header mirroring bytes should be configured for this mapper has unfortunately been rather ambiguous in the past, but was recently more properly defined and I updated Mesen to respect that definition.

Please make sure your iNES header config matches what you need based on this table:
http://wiki.nesdev.com/w/index.php/UNROM_512#Nametable_Configuration

**Comment by Kitsu-neechan** [comment] 2019-06-25 09:20
all nesmaker games are by design set to vertical mirroring (byte 6 of the header is 0x00)
as is this one. Downloaded 0.9.8 and indeed the same happens to my own project with it.
im not really much of an expert on the matter either but i can try to look into the code a bit more if you let me know what exactly im looking at. 

in the meantime, here's a video showing the thing in 0.9.8, it appears to actually mirror horizontally.
(hex editor on the video shows the rom's header)

https://youtu.be/0CKhu6NZPLI

**Comment by SourMesen** [comment] 2019-06-25 23:52
So yea, that was a pretty dumb mistake.  The table on the wiki is describing the nametables' "arrangement" instead of mirroring, which is the opposite.  The rest of the wiki tends to talk about the mirroring instead, so I ended up reversing the horizontal and vertical configurations because of this.  I was fixing a 4-screen mirroring game at the time, and since the only other mapper 30 game I have on hand seems to just use a single screen with no scrolling, it works fine with both horizontal & vertical mirroring.

It should be fixed by 4c701ad6cffe81056fc58dde69b9fc75ad79c801 - can either of you test the next appveyor dev build (0.9.8.4) to verify that the games are working properly now?  If everything seems correct, I'll rebuild 0.9.8 and reupload a new version of it (again).

**Comment by Kitsu-neechan** [comment] 2019-06-26 00:11
I grabbed 0.9.8.4 and gave it a spin and now the behavior is back how it was (AKA: it works.)

however, this raises the question of what's going on in here in general, because if i read the nesdev wiki about this correctly, it says that the 2 bits of byte 6 control the mirroring mode in a following configuration: %xxxx0xx0 for vertical and %xxxx0xx1 for horizontal, but as the below screenshots appear to indicate, the effect is actually the opposite (line 7 is the byte that contains the mirror bits)

as seen, setting them to 00 causes a horizontal mirror, and setting them to 01 causes vertical mirror, which according to the wiki should be exactly the opposite, yet the rom functions just fine when flashed to a INL mapper 30 cartridge.

![mirror_00](https://user-images.githubusercontent.com/27159805/60141871-0d0d4800-97c0-11e9-9365-7d39a0fe968c.png)

![mirror_01](https://user-images.githubusercontent.com/27159805/60141876-10a0cf00-97c0-11e9-8289-b808ddc0a3c0.png)

**Comment by SourMesen** [comment] 2019-06-26 00:30
That's the thing - the wiki says `0 = vertical arrangement`, but `vertical arrangement` is actually the same thing as horizontal **mirroring**.  This is how I ended up inadvertently reversing both settings when I updated the code for 0.9.8.

**Comment by Kitsu-neechan** [comment] 2019-06-26 00:33
ah gosh darn it, i fell into the same trap!
it's extra confusing for me because im just a scrubby nesmaker dev (huehue!) and the notes on the header code as you can see also denote that horizontal mirroring is intended, but in reality the header is and was always configured for vertical mirroring (as it should be because the engine doesnt even work with h-mirror)

**Comment by SourMesen** [comment] 2019-06-26 01:00
Alright - I've reuploaded a new build of 0.9.8 on both github and the website. If you redownload 0.9.8 manually, the problem should be fixed.  Anyone that downloaded the buggy version of 0.9.8 will need to redownload it, unfortunately.

**Comment by Kitsu-neechan** [comment] 2019-06-26 01:04
I informed nesmaker community that the late appveyor build fixes the issue, but i'll add to that, that the main download also works now. thanks for the effort and sorry for the trouble :P

**Comment by SourMesen** [comment] 2019-06-26 01:10
Awesome - thanks for testing & letting people over on the Nesmaker forums aware of it!
I changed the title and will keep this issue opened for a couple more days to help make more people aware of the issue/fix.

Sorry for this - unfortunately I don't have a QA team :p

**Comment by Kitsu-neechan** [comment] 2019-06-26 01:14
aint nobody got time for QA teams :p 
that's what us peasants are for!
at any rate, i wrote everything relevant up to the community forum and it appears to have gone to the facebook too already so it should catch up the nesmaker users fairly fast.
i also wrote a clean version of the header intended for this and notated it properly for future reference.

**Comment by SourMesen** [comment] 2019-07-08 01:07
Thanks for your help on this one, too!
Closing this now since it's hopefully been opened long enough for most users that were getting the problem to have noticed.

**Closed by SourMesen** 2019-07-08 01:07 UTC
Labels: bug
