### ISSUE TITLE
Fullscreen cropping

### ISSUE THREAD

**Issue by sharknnth** [SourMesen/Mesen#295] opened 2018-01-01 17:56 UTC
Whenever I go into fullscreen it runs in a cropped window, I wasn't getting this in the last version.

**Comment by SourMesen** [comment] 2018-01-01 18:00
Can you post a picture/screenshot of what you mean?  Fullscreen mode is working as it used to on my end, so there may be something in your settings/etc that is causing the issue.

**Comment by sharknnth** [comment] 2018-01-01 19:29
![mesen cropping](https://user-images.githubusercontent.com/20363914/34470481-fe29d078-ef29-11e7-92c1-213c2490cb7a.png)
This is what's happening and my overscans are all set at 0.

**Comment by SourMesen** [comment] 2018-01-02 16:18
The image is at 4k resolution (3840x2160) but the NES's picture inside it appears to be 2560x1440 which is also a popular resolution for monitors.  This is probably not a coincidence - do you have 2 monitors plugged in with different native resolutions?

**Comment by sharknnth** [comment] 2018-01-02 18:33
No, I'm just using one 4k HDTV.

**Comment by SourMesen** [comment] 2018-03-25 20:39
I haven't been able to reproduce or fix this yet (I'm hoping to be able to do so before the next release)
For now, closing this as a duplicate of #312 (just to clean up the issue list)

**Closed by SourMesen** 2018-03-25 20:39 UTC
