### ISSUE TITLE
Full screen is small without a filter on.

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#78] opened 2016-12-12 06:00 UTC
Full screen is small without a filter on. Here is a video.

https://www.youtube.com/watch?v=8dayX8H8ehU&feature=youtu.be

**Comment by SourMesen** [comment] 2016-12-13 01:51
Thanks for always testing and reporting issues, helps a lot! :)
Someone on reddit mentioned a similar issue as well - this is probably new to 0.6.0.
I'll take a look at it soon.

**Comment by SourMesen** [comment] 2016-12-23 04:10
I'm not completely sure because I wasn't able to reproduce the problem, but this is hopefully fixed by b63c1f9c4e61031de4576c0723357c1eb55e56b8.
If you still get the bug after the next Mesen release, please reopen this issue.  Thanks!

**Closed by SourMesen** 2016-12-23 04:10 UTC
Labels: bug

**Comment by Cibomatto2002** [comment] 2016-12-25 07:02
The bug is still in 0.6.1. If you set the video size to 1 with a filter off you will get a small picture setting it to  2 makes it bigger setting it to 3 will fill the screen. Maybe this will help i'm using a Element ELEFW328 32" 720p 60Hz Class LED HDTV.

![1 1](https://cloud.githubusercontent.com/assets/21169038/21470063/badd2b06-ca3d-11e6-8024-7302e1d62730.jpg)

![1 2](https://cloud.githubusercontent.com/assets/21169038/21470064/be4fde64-ca3d-11e6-86e2-81b52be48442.jpg)

![1 3](https://cloud.githubusercontent.com/assets/21169038/21470065/c1fe9852-ca3d-11e6-992a-b66573df2696.jpg)
