### ISSUE TITLE
[Linux] Black Screen when running from command line

### ISSUE THREAD

**Issue by andre-paris** [SourMesen/Mesen#480] opened 2018-08-24 14:33 UTC
Hi,
I'm on Ubuntu 18.04 and when running Mesen from command line like this
```mono Mesen.exe alter_ego.nes```
It starts with a black screen with the sound on background. I've to hit Ctrl+T (Power Cycle) to work properly.
Thanks in advance.

**Comment by indexitis** [comment] 2018-08-24 17:40
I think this is a duplicate of #319. May I ask what graphics card and driver you are using? And whether you must resize the window before cycling the power?

**Comment by andre-paris** [comment] 2018-08-25 20:56
It's a GeForce 830M with nvidia driver version 390.48. I don't need to resize the window.

**Comment by SourMesen** [comment] 2018-08-26 01:29
Yea, this is most likely a duplicate of #319 - I still haven't found a solution for it, unfortunately, but I'm able to reproduce the issue so hopefully I can find a fix/workaround eventually.

**Closed by SourMesen** 2018-08-26 01:29 UTC
Labels: duplicate
