### ISSUE TITLE
Fullscreen bug

### ISSUE THREAD

**Issue by sharknnth** [SourMesen/Mesen#76] opened 2016-12-11 14:30 UTC
There's a bug when going fullscreen that prevents the picture from filling the full frame.

**Comment by SourMesen** [comment] 2016-12-11 14:41
Thanks for the report - As far as I can tell though, this is working as expected on my end.
What aspect ratio/overscan settings are you using?
Could you attach a screenshot of the bug?

**Comment by sharknnth** [comment] 2016-12-11 20:26
My settings are widescreen 16:9 for the aspect ratio and the overscan settings are 0 for the left and right and 8 for the top and bottom. Here's a screenshot of how it appears in fullscreen. Thanks
![mesen fullscreen](https://cloud.githubusercontent.com/assets/20363914/21083059/107b628e-bfe0-11e6-9183-6da47251db54.jpg)

**Comment by sharknnth** [comment] 2016-12-11 20:37
Setting all the overscan options to 0 seems to fix it.

**Comment by SourMesen** [comment] 2016-12-23 04:10
I'm not completely sure because I wasn't able to reproduce the problem, but this is hopefully fixed by b63c1f9c4e61031de4576c0723357c1eb55e56b8.
If you still get the bug after the next Mesen release, please reopen this issue.  Thanks!

**Closed by SourMesen** 2016-12-23 04:10 UTC
Labels: bug
