### ISSUE TITLE
Opening a game and pausing it on the first frame then rewinding crashes and locks Mesen.

### ISSUE THREAD

**Issue by RumblePen** [SourMesen/Mesen#673] opened 2019-09-12 13:49 UTC
![crash](https://user-images.githubusercontent.com/46263344/64789571-98d27d00-d542-11e9-81ec-c95603fc0d0e.png)

**Comment by SourMesen** [comment] 2019-10-07 01:15
Thanks for the report (and sorry for the delay!) - this is actually something that someone else reported to me a few weeks ago.  If I recall correctly, it's a regression due to another change done in 0.9.8.

I should be able to take a look relatively soon.

**Comment by SourMesen** [comment] 2019-11-14 00:43
This should be fixed in the latest build - thanks for the report!

**Closed by SourMesen** 2019-11-14 00:43 UTC
Labels: bug
