### ISSUE TITLE
Can't lower audio latency below 100ms (Windows 10 Pro AU x64)

### ISSUE THREAD

**Issue by Nicholas-Steel** [SourMesen/Mesen#70] opened 2016-12-04 17:36 UTC
Realtek ALC1200 integrated audio chip with the latest audio driver. This problem is currently the biggest roadblock to me switching over to your emulator for gaming. Really annoying hearing sound fx way late.

**Comment by SourMesen** [comment] 2016-12-04 17:48
This is technically by design as lower values can sometimes cause audio to distort slightly (at least, on my computer)

You can try lowering it by editing the settings.xml file (in the Documents\Mesen folder) manually and changing the value for AudioLatency to a lower value (don't open the audio config window after doing this though, or it will reset to 100ms again).  This configures the size of the audio buffer.

If you find that lower values work correctly for you, let me know and I'll change the UI's minimum limit to something that makes more sense.

**Comment by Nicholas-Steel** [comment] 2016-12-05 05:56
70ms seems to be fine in Mesen, below 70ms produces crackling and I dunno why it would since most other emulators accept such low latency without producing crackling. The ideal latency would be around 40-60ms.

**Comment by SourMesen** [comment] 2016-12-06 01:07
I made a build that contains a lot of changes to the way the sound is output.
With these changes, I seem to be able to go down to about 20ms with no or little crackling.

I'm not quite ready to commit this as a fix since it could cause sound desynchronization, or permanent sound crackling (e.g until sound settings are changed or the game reset) if the new logic isn't flawless.

Could I ask you to test it on your end?
You can grab a copy of it here: [download](http://www.mesen.ca/MesenAudioLatency.zip)

I'd mostly like to know:
a) does it work correctly at all on your end?
b) how low can you set the latency before you start hearing crackling?
c) does the sound ever get out of sync or start crackling for a long period of time if you play the same game for a while without pausing/changing sound settings?

If you play with this build for a while and can confirm that it fixes the latency without causing issues, I'll commit the change and it should be in the next release of Mesen.

**Comment by Nicholas-Steel** [comment] 2016-12-06 07:51
1) Yes, it works fine at least in Stereo Delayed mode with the default 15ms delay.
2) Yeah, 20ms works fine which is great. Below 20ms introduces crackling/stutter to the audio.
3) I played Super Mario Bros. 1 for 23 minutes, the game was paused for 7 minutes during this playthrough (in-game pause, I pressed Start). I noticed no desynchronization of the audio though I'm not 100% certain of what you mean by desynchronization. I recorded it with Nvidia Shadowplay and can upload the footage somewhere if you wanted.

**Comment by SourMesen** [comment] 2016-12-07 04:27
Thanks for testing - looks promising if it works on your end too.
I'll try the change on my laptop when I get the chance - if it seems fine, I'll commit the change and it'll be in the next version.

**Comment by SourMesen** [comment] 2016-12-09 15:31
This is fixed by 3f3b3ffb3c024418745cafc6e1ee5cf19564e208
Thanks again for testing - please let me know if you get any sound problems with the lower latency in the next release.

**Closed by SourMesen** 2016-12-09 15:31 UTC
Labels: enhancement

**Comment by Nicholas-Steel** [comment] 2016-12-10 04:27
If I do notice an issue, should I make a new bug report or post here/re-open this report?

**Comment by SourMesen** [comment] 2016-12-21 23:11
If you notice any issue with the lower latency settings, just reopen this one please.
