### ISSUE TITLE
HD Pack Builder PNG Files Transparency

### ISSUE THREAD

**Issue by checkas** [SourMesen/Mesen#842] opened 2020-05-29 06:51 UTC
When recording the images I'm noticing that I'm not getting transparent png files and in turn if you load the game with those files the game is unplayable.  Any ideas what might be causing this?

**Comment by heckez-sys** [comment] 2020-05-29 10:07
dont know but i had the same issue

**Comment by SourMesen** [comment] 2020-05-29 13:17
Thanks for the report - this is most likely a duplicate of #778 which is already fixed in the latest dev builds.

**Closed by SourMesen** 2020-05-29 13:17 UTC
Labels: duplicate

**Comment by checkas** [comment] 2020-05-29 15:05
So where do we get the build?Sent from my Sprint Samsung Galaxy S9+.
-------- Original message --------From: SourMesen <notifications@github.com> Date: 5/29/20  8:18 AM  (GMT-06:00) To: SourMesen/Mesen <Mesen@noreply.github.com> Cc: checkas <justin@justintoney.com>, Author <author@noreply.github.com> Subject: Re: [SourMesen/Mesen] HD Pack Builder PNG Files Transparency (#842) 
Thanks for the report - this is most likely a duplicate of #778 which is already fixed in the latest dev builds.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SourMesen/Mesen/issues/842#issuecomment-635967314",
"url": "https://github.com/SourMesen/Mesen/issues/842#issuecomment-635967314",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SourMesen** [comment] 2020-05-29 15:19
@checkas  They are linked in the readme.

**Comment by checkas** [comment] 2020-05-29 15:27
Okay so I don't see that.  Please tell me where to look.

**Comment by SourMesen** [comment] 2020-05-29 15:47
https://github.com/SourMesen/Mesen/blob/master/README.md#development-builds
