### ISSUE TITLE
fullscreen res issue with nvidia after MesenDevWin-0.9.8.79

### ISSUE THREAD

**Issue by jjfmz42015** [SourMesen/Mesen#743] opened 2019-12-29 02:50 UTC
So I use nvidia.

MesenDevWin-0.9.8.76 exclusive fullscreen would work but sometimes require multiple tries.

in MesenDevWin-0.9.8.77 this was fixed.

in MesenDevWin-0.9.8.79 problem back.

**Comment by SourMesen** [comment] 2019-12-29 03:08
There is no difference between builds 77 and 79 on Windows (the only changes to the code were 100% Linux-specific).  If the problem is still visible on build 79, then it was not truly fixed on build 77.

**Comment by SourMesen** [comment] 2020-04-20 00:27
Unfortunately, since I can't reproduce this, I really have no way of fixing this at the moment.
Unless you have a good reason to be using exclusive fullscreen mode, I would not use it - it only exists in case someone really *has* to use it due to other issues.

**Closed by SourMesen** 2020-04-20 00:27 UTC
Labels: bug, cannot reproduce
