### ISSUE TITLE
Memory Tools Crash when Using Table File with Multi-Character Entries

### ISSUE THREAD

**Issue by Arstan-Neckbeard** [SourMesen/Mesen#536] opened 2018-12-02 06:35 UTC
Having issues with Mesen's Memory Tools display crashing at a certain point while the game is running, specifically when using a table file with entries such as:

> FC=[CR_EOS]

I'm assuming it's related to the length of the entries in some way, attached is an image of the crash and the table file.

> An unexpected error has occurred.
> 
> Error details:
>  System.Index.OutOfRangeException: Index was outside the bounds of the array.
>   at Be.Windows.Forms.HexBox.PaintHexAndStringView(Graphics g, Int64 startByte, Int64 endByte)
>   at Be.Windows.Forms.HexBox.OnPaint(PaintEventArgs e)
>   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
>   at System.Windows.Forms.Control.WmPaint(Message& m)
>   at System.Windows.Forms.Control.WndProc(Message& m)
>   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

[DQJ_2.tbl.txt](https://github.com/SourMesen/Mesen/files/2636645/DQJ_2.tbl.txt)

![mesenmemorycrash](https://user-images.githubusercontent.com/8083295/49336560-7fbf9780-f5d2-11e8-9f42-2876f6ff07b3.PNG)

**Comment by SourMesen** [comment] 2018-12-03 06:54
Thanks for the bug report!
This was actually caused by using multi-byte replacement rules in TBL files.  e.g these:
```
F0BF=[Keys]
F0C0=[Herbs]
F0C5=[CHP]
F0C6=[CMP]
```

This is fixed by c901226f8cfaa2b6d7d6d7a47d83486317032145 - the next build to show up on appveyor in a few minutes should contain the fix.

**Closed by SourMesen** 2018-12-03 06:54 UTC
Labels: bug
