### ISSUE TITLE
Non-NES/FC/FDS games crashing

### ISSUE THREAD

**Issue by tbmny** [SourMesen/Mesen#450] opened 2018-08-06 00:18 UTC
As of at least 0.9.6, Mesen crashes frequently if you try to load a non-NES game. On older versions, the typical response happens which is that the emulator puts an error message at the bottom, but now it's crashing as that text is appearing. This is also happening when I try to play Vs. Super Mario Bros., but that may just be me not understanding how to run Vs. System games in Mesen.

**Comment by tbmny** [comment] 2018-08-06 15:28
Anything. SNES games, Genesis games, etc. I know obviously the fix is just to not load the wrong game, but I just wanted to point it out since this isn't the correct behavior.

**Comment by SourMesen** [comment] 2018-08-06 21:05
When it crashes, before you force close Mesen, could open up the task manager, right-click on Mesen and select "Create dump file"?  This should create a .dmp file in a temporary folder - if you could send that my way, it should help me get a better understanding of what's causing it to crash on your end (since I can't reproduce the crash on my computer)

**Comment by tbmny** [comment] 2018-08-06 21:40
It doesn't give me that chance. It just immediately crashes to the desktop so there's no opportunity to do that.

https://streamable.com/nr72r

Anyway, I narrowed it down to what I think is the cause. It's only happening to games with recorded sprites from the HD pack builder.

**Comment by SourMesen** [comment] 2018-08-06 22:35
Thanks for taking the time to figure out how to reproduce it!
This is fixed by 3c30b239587d53ed0b78db659e808e2376532c04

**Closed by SourMesen** 2018-08-06 22:35 UTC
