### ISSUE TITLE
Problem loading some FDS roms.

### ISSUE THREAD

**Issue by PinkLouie** [SourMesen/Mesen#171] opened 2017-05-21 09:57 UTC
These roms are not unlicensed.

Adian no Tsue (Japan) (Beta) - Disk Set Err 1, but works
Adian no Tsue (Japan) - Disk Set Err 1, but works
Big Challenge! Juudou Senshuken (Japan) - Mesen stops responding and crashes entirelly!
Chitei Tairiku Ordola (Japan) - Disk Set Err 1, but works
Dead Zone (Japan) (Beta) - Disk Set Err 1, but works
Dead Zone (Japan) - Disk Set Err 1, but works
Famicom Mukashibanashi - Shin Onigashima - Kouhen (Japan)
Famicom Mukashibanashi - Yuuyuuki - Kouhen (Japan)
Famicom Tantei Club - Kieta Koukeisha - Kouhen (Japan) - Err. 20
Fuuun Shourin Ken - Ankoku no Maou (Japan) - 1
Gall Force - Eternal Story (Japan) - 1
Monitor Puzzle Kinetic Connection, The - Kineco (Japan) - Err 1
Super Lode Runner (Japan) - Err 1
Tantei Jinguuji Saburou - Kiken na Futari - Kouhen (Japan) - Err. 08
Time Twist - Rekishi no Katasumi de... - Kouhen (Japan)

Doremikko (Japan) [b] - Err 01
Famicom Tantei Club Part II - Ushiro ni Tatsu Shoujo - Kouhen (Japan) [b] - Err. 20
Mahjong Kazoku (Japan) [b] - Disk Set Err 1, but works
Monitor Puzzle Kinetic Connection, The - Kineco II (Japan) (Disk Writer) [b]
Putt Putt Golf (Japan) [b] - Disk Set Err 1, but works

Note: I enabled "automatically switch disks".

**Comment by SourMesen** [comment] 2017-05-21 13:00
"Automatically switch disks" will sometimes cause Disk Set Err 1, among other things.
It can cause issues, which is why the option is not enabled by default.

The majority of these issues are most likely caused by the auto switch disk option and fixed by f83e7ce5b285094fbf19ff9c7468f8e51427dfcc.
I would suggest you stop testing FDS games in 0.9.0 since 0.9.0 introduced a bug in FDS emulation (whether or not the auto switch option is enabled), which is fixed by f83e7ce5b285094fbf19ff9c7468f8e51427dfcc.

**Comment by SourMesen** [comment] 2017-05-22 15:20
I've fixed the 2 bugs I was able to confirm:
-Big Challenge crash (3da14db83d87f29c64f182faa65d43f52ff07fb0)
-Super Lode Runner not starting (3a55cfeea907642e6b4eefb5f9bcf303946660e0)

Also, the "automatically select disk" option is not perfect (though it should be a bit better in the next release), so it's possible that it may need to be manually disabled in some games.

**Closed by SourMesen** 2017-05-22 15:20 UTC
