### ISSUE TITLE
[Libretro] Savestates not working on android

### ISSUE THREAD

**Issue by fr500** [SourMesen/Mesen#331] opened 2018-02-25 04:17 UTC
Managed to get a quick test case going after the build worked and I noticed savestates don't work. I'm getting a crash on load state.

I'll try to investigate.

**Comment by fr500** [comment] 2018-02-25 04:24
```
02-24 23:24:24.875 20716 20734 F libc    : Fatal signal 7 (SIGBUS), code 1, fault addr 0x575763da in tid 20734 (Thread-2)
02-24 23:24:24.876   228   228 W         : debuggerd: handling request: pid=20716 uid=10112 gid=10112 tid=20734
02-24 23:24:24.876 20957 20957 W debuggerd: type=1400 audit(0.0:66): avc: denied { search } for name="com.retroarch" dev="mmcblk0p29" ino=516760 scontext=u:r:debuggerd:s0 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=dir permissive=0
02-24 23:24:24.938 20957 20957 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-24 23:24:24.938 20957 20957 F DEBUG   : LineageOS Version: '14.1-20170919-UNOFFICIAL-loki'
02-24 23:24:24.938 20957 20957 F DEBUG   : Build fingerprint: 'NVIDIA/loki_e_lte/loki:7.0/NRD90M/1749719_832.2408:user/release-keys'
02-24 23:24:24.938 20957 20957 F DEBUG   : Revision: '0'
02-24 23:24:24.938 20957 20957 F DEBUG   : ABI: 'arm'
02-24 23:24:24.939 20957 20957 F DEBUG   : pid: 20716, tid: 20734, name: Thread-2  >>> com.retroarch <<<
02-24 23:24:24.939 20957 20957 F DEBUG   : signal 7 (SIGBUS), code 1 (BUS_ADRALN), fault addr 0x575763da
02-24 23:24:24.939 20957 20957 F DEBUG   :     r0 000001e2  r1 575763da  r2 000001da  r3 00000000
02-24 23:24:24.939 20957 20957 F DEBUG   :     r4 5217dc04  r5 5217e540  r6 00000008  r7 00000008
02-24 23:24:24.939 20957 20957 F DEBUG   :     r8 5217e558  r9 4aae26a0  sl 4aae269e  fp 4aae2240
02-24 23:24:24.939 20957 20957 F DEBUG   :     ip 8ba38d2c  sp 4aae2208  lr 8b836a84  pc 8b749978  cpsr 800e0010
02-24 23:24:24.945 20957 20957 F DEBUG   :
02-24 23:24:24.945 20957 20957 F DEBUG   : backtrace:
02-24 23:24:24.946 20957 20957 F DEBUG   :     #00 pc 00154978  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #01 pc 00241a80  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #02 pc 00241970  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #03 pc 002417e8  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #04 pc 002416e0  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #05 pc 00241594  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #06 pc 002413d8  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #07 pc 002411ac  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #08 pc 00240930  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #09 pc 002678c0  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #10 pc 0018580c  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #11 pc 00185a74  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #12 pc 00148fb0  /data/data/com.retroarch/cores/mesen_libretro_android.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #13 pc 0021ce24  /data/app/com.retroarch-1/lib/arm/libretroarch-activity.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #14 pc 002d28c0  /data/app/com.retroarch-1/lib/arm/libretroarch-activity.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #15 pc 002d2c60  /data/app/com.retroarch-1/lib/arm/libretroarch-activity.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #16 pc 001bf8d8  /data/app/com.retroarch-1/lib/arm/libretroarch-activity.so (rarch_main+440)
02-24 23:24:24.946 20957 20957 F DEBUG   :     #17 pc 002d1e58  /data/app/com.retroarch-1/lib/arm/libretroarch-activity.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #18 pc 00202418  /data/app/com.retroarch-1/lib/arm/libretroarch-activity.so
02-24 23:24:24.946 20957 20957 F DEBUG   :     #19 pc 00047e63  /system/lib/libc.so (_ZL15__pthread_startPv+22)
02-24 23:24:24.946 20957 20957 F DEBUG   :     #20 pc 00019f3d  /system/lib/libc.so (__start_thread+6)
```

**Comment by xTMODx** [comment] 2018-02-26 01:50
here is my raw log of the crash https://paste.ee/p/lJSFk

**Comment by xTMODx** [comment] 2018-04-11 20:53
@SourMesen is there anything i could help with to fix this? I really wait for it to fix so i can use the core on my android

**Comment by SourMesen** [comment] 2018-04-11 21:15
I currently do not have any way to debug this easily - unless someone else with better knowledge of android software tries to debug the issue on their end, or gives me more detailed information about the crash, it's unlikely I can fix this anytime soon.

**Comment by bparker06** [comment] 2018-04-12 11:42
@fr500 Is this the Shield Tablet? It and a bunch of other random android devices have kernels that don't allow unaligned memory access. Same thing happens with bsnes and some other cores.

https://github.com/libretro/bsnes-libretro/issues/42

It may be possible to fix this in software with a gcc-specific alignment keyword (I think one core was fixed this way already), the problem is finding out where it's needed and why.

**Comment by xTMODx** [comment] 2018-04-12 17:47
nice hope we can fix it!

**Comment by fr500** [comment] 2018-04-12 20:07
@bparker06 it was on my Tegra X1 device

**Comment by xTMODx** [comment] 2018-04-14 08:38
@bparker06 i think i found the compiler-specific alignment in here https://github.com/libretro/QuickNES_Core/pull/41 can you confirm this? and maybe someone can test it

**Comment by SourMesen** [comment] 2018-06-25 00:14
As of the latest android build, this should be fixed (3e6f10757c750f342868e3ba8c0a271dababe973).  Thanks for the unaligned memory hint, wouldn't have noticed it in the crash myself!

Unsure if the "update core" option will work at the moment since the build in the "latest" folder on the buildbot was built manually by bparker (thanks!), but the next android build the buildbot makes should be working properly.

**Closed by SourMesen** 2018-06-25 00:14 UTC
Labels: bug, libretro

**Comment by bparker06** [comment] 2018-06-25 00:49
The Core Updater only grabs from the "latest" folder, so it should work fine.

**Comment by xTMODx** [comment] 2018-06-25 09:22
Awesome! Just tested it and it works fine :) thanks
