### ISSUE TITLE
0.9.8 color emphasis is broken.

### ISSUE THREAD

**Issue by Kitsu-neechan** [SourMesen/Mesen#640] opened 2019-07-07 10:21 UTC
More or less as it says.

here's a video displaying the code i use for setting the emphasis,
along with running the same rom with both mesen 0.9.6.34 and 0.9.8.4
the new version appears to have opposite effect for the color emphasis to the expected, as in
setting all the emphasis bits brights up the screen instead of darkening it.

https://youtu.be/-e4pALWlrbg

the video quality is sorta shit (watch in 1080p) so the emphasis doesnt really show much at all when darkening the screen using 0.9.6.34, but you can clearly see that the effect is not what it should using 0.9.8

**Comment by SourMesen** [comment] 2019-07-07 12:40
Thanks for the report.
The palette for emphasis bits was no longer getting generated at all unless the user had selected a palette at least once in the video configuration in the past. I think that's probably the case here, but I'm not 100% sure.

I just committed a fix for this, could you check the latest dev build and see if the problem is solved on your end?

**Comment by Kitsu-neechan** [comment] 2019-07-07 13:24
I will test this but it seems consistent with the behavior im getting, I went through options to check
if something was off or whatnot and after that it started working so propably cycling through the palette
selection here fixed it here too.

I grabbed 0.9.8.5 from appveyor and it worked out of the box so that appears to be all good.
I'll let you know if I run into further issues with it.

**Comment by SourMesen** [comment] 2019-07-08 01:01
Great - thanks for testing!

**Closed by SourMesen** 2019-07-08 01:01 UTC
Labels: bug

**Comment by Kitsu-neechan** [comment] 2019-07-16 18:47
@SourMesen 
This is not as much of a bug report than just a general question, but i finally got my 
mapper 30 cart and got to test my project on actual hardware, and i noticed that the color emphasis
is orders of magnitude stronger on real hardware than it is on mesen.

is the color emphasis somehow adjustable by users or is it hardcoded to the emulator?
I can't help but feeling it should be made slightly stronger on the emulator, atleast on the darken 
(setting all bits) part.

**Comment by SourMesen** [comment] 2019-07-16 20:24
As far as I understand it, how the emphasis bits look on a specific TV actually can vary to some extent, much like there is no "true" palette for the NES, only approximations.
e.g: see: https://forums.nesdev.com/viewtopic.php?f=3&t=18416
Which essentially says that for this particular user, Mesen's emphasis formula looked like it was the most accurate. (FYI the emphasis bit calculation is pretty simple in Mesen and probably not that accurate in any form or manner).

This is why I've added support for 512-color palette files in 0.9.8, though.  You can load up a 512-entry palette file which lets you specify the exact color used for all colors, with all emphasis bit combinations. (64*8)

**Comment by Kitsu-neechan** [comment] 2019-07-16 20:36
I figured it's something of the sort. And god knows, maybe it's just my monitor an monitor settings
that makes mesen's emphasis look particularly dull on my pc. (shatterhand uses various color modes with emphasis and it looks pretty disdinct) but in my own game i only use the darken and it always struck me as odd that it's practically unnoticeable, whereas my TV actually dims it so much it's almost like a straight 50% cut.

that said, the nesdev thread was a good insight on this and the fact that you have a method for manual customizing of the effect is more than I could ask so i'll definitely take a look into that.
