### ISSUE TITLE
PPU viewer window problem after zooming out

### ISSUE THREAD

**Issue by raousoft** [SourMesen/Mesen#850] opened 2020-06-21 17:48 UTC
Hi dear Sour,

I really appreciate the X2 zoom option in PPU Viewer, it helps me read Nametables easily.However, when I click on it again and zoom out, the window gets shrunk like this:

https://drive.google.com/file/d/1dkxj2IV_OXwBbm6-4_ZenKDWms0B-k7_/view

So I have to close the PPU Viewer and open it again every time. (it's not that of a problem for me, but just wanted to share that experience).

Tested on `DevWin-0.9.9.56` , but I remember testing it on earlier builds too.

**Comment by SourMesen** [comment] 2020-06-21 22:59
Thanks for the report! This is a duplicate of #715.
Basically, if the 2x button makes the ppu viewer bigger than your screen's resolution, it won't work as expected when you try to make it smaller again.
I'm still not sure of the best way forward here, but I'm considering just reworking the ppu viewer to be more like mesen-s' which is a lot more flexible in terms of zooming or window size (which would let me remove the 2x button entirely)

**Closed by SourMesen** 2020-06-21 22:59 UTC
Labels: duplicate
