### ISSUE TITLE
0.8.1 Crashes When Opening Debugger Sometimes

### ISSUE THREAD

**Issue by cacciatc** [SourMesen/Mesen#157] opened 2017-05-06 22:48 UTC
I just updated from 0.7.0 to 0.8.1 and Mesen crashes when I do the following:

1. Start Mesen.
2. Drag and drop a ROM for my game Neb's & Debs (a game for which I have used the debugger before).
3. Open Tools->Debugger.

The emulator crashes with a error window stating:
__Mesen (Beta) has stopped working.__

Debugging with VS, but no code loaded gives me the following exception:

>An unhandled exception of type 'System.AccessViolationException' occurred in Mesen.exe
> Additional information: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

Note, doing so with other games for which I have never debugged before does not cause this error. So I am guessing it perhaps a pathing issue with some debugging file?

If I have time I will try to build from source, run, and debug later today.

**Comment by SourMesen** [comment] 2017-05-06 22:57
Thanks for the report!
If I had to take a guess, it's probably a crash that was caused by 6a57fa5cb354515b5d5dc360c06bd4349238297d (in 0.8.0) and subsequently fixed by 1cefdd29a2d14ee35febc199c8e6b399b8f46105 (caused the disassembler to try and disassemble out-of-bounds memory)

Assuming you're on Windows, you can try out this build from earlier today: [link](https://www.mesen.ca/MesenDebuggerFix.zip)
Let me know if it fixes the crash.

**Comment by cacciatc** [comment] 2017-05-06 23:05
Thanks @SourMesen. I will try the build. I just built from source and ran; the exception is thrown by
https://github.com/SourMesen/Mesen/blob/master/GUI.NET/Debugger/LabelManager.cs#L72

**Comment by cacciatc** [comment] 2017-05-06 23:08
The new build dies at startup for me on Win 10:

![mesen-bug](https://cloud.githubusercontent.com/assets/149836/25776558/2698d41c-3276-11e7-8387-9d088a4e3909.png)

**Comment by SourMesen** [comment] 2017-05-06 23:09
Thanks, that's good to know - and a good reason why I shouldn't be sending half-tested builds :)

The debugger issue must be a different crash then.
In the Documents\Mesen\Debugger folder, there should be a [RomName].Workspace.xml file for your rom which contains labels, breakpoints, etc. - could you attach it here?  I'm guessing one of the labels must be causing the crash.

**Comment by cacciatc** [comment] 2017-05-06 23:20
Contents of XML can be found in this gist: https://gist.githubusercontent.com/cacciatc/d041a6ed4e36aa8649e06eb4efcfe125/raw/392b536ba2edd4f8b73d40c8b11ccd31f03cba81/main.Workspace.xml

Note, removing said file and the corresponding CDL for good measure fixes the issue.

No worries about half-tested builds--I appreciate your effort with Mesen!

**Comment by SourMesen** [comment] 2017-05-06 23:59
Thanks - I can't reproduce a crash on my end though (with either 0.8.1 or latest).
I have a feeling it might have been the CDL file (the CDL file existing will cause the disassembler to disassemble everything it knows to be code based on previous debugging sessions - so it's likely to trigger the bug I mentioned earlier).

Could you try this updated [build](https://www.mesen.ca/MesenDebuggerFix.zip) - it should fix the Windows 10 crash you were getting at startup.  If you still have the CDL file, could you try putting it and the XML file back in the Debugger folder and seeing if any crash occurs with this build?  No worries if you don't have it anymore, though - I'd be happy with just confirmation that the emulator doesn't crash on startup!

**Comment by cacciatc** [comment] 2017-05-07 02:27
> Could you try this updated build - it should fix the Windows 10 crash you were getting at startup. If you still have the CDL file, could you try putting it and the XML file back in the Debugger folder and seeing if any crash occurs with this build? No worries if you don't have it anymore, though - I'd be happy with just confirmation that the emulator doesn't crash on startup!

I tried the build and can confirm that neither crash occurred (using the old XML and CDL files).

**Comment by SourMesen** [comment] 2017-05-07 03:10
Great, thanks for testing!
Let me know if you find any other issues.

**Closed by SourMesen** 2017-05-07 03:10 UTC
