### ISSUE TITLE
Libretro Mac crash

### ISSUE THREAD

**Issue by zoharxero** [SourMesen/Mesen#306] opened 2018-01-07 17:44 UTC
Crash on libretro for Mac, when loading rom:

```

[INFO] === Build =======================================
Capabilities: MMX MMXEXT SSE1 SSE2 SSE3 SSSE3 SSE4 SSE4.2 AVX AVX2 AES
Built: Dec 25 2017
[INFO] Version: 1.7.0
[INFO] =================================================
[ERROR] Serious problem. RetroArch wants to load libretro cores dynamically, but it is already linked.
[ERROR] This could happen if other modules RetroArch depends on link against libretro directly.
[ERROR] Proceeding could cause a crash. Aborting ...
[ERROR] Fatal error received in: "init_libretro_sym()"
[ERROR] This core requires a content file.

[ERROR] failed_to_start_audio_driver
[1]    1340 segmentation fault  /Applications/RetroArch.app/Contents/MacOS/RetroArch --verbose
```

**Comment by SourMesen** [comment] 2018-01-07 18:11
Thanks - I don't think anybody has actually tested the OSX core yet. It builds, but I don't think anybody has tried running it at all, so you might be the first.
Just to be sure, did you build this yourself, or did you download the core from retroarch?

**Comment by zoharxero** [comment] 2018-01-07 18:29
I downloaded the core from retroarch. I tried to build it but it has the same error.

**Comment by meunierd** [comment] 2018-03-12 14:12
+1 I'm also experiencing this on High Sierra, downloading from the Online Updater.

**Comment by SourMesen** [comment] 2018-03-12 21:56
There is not much I can personally do to help here - I do not have access to any mac (and didn't have any involvement in building the core for macs).  @fr500 and @bparker06 worked on getting the buildbot to compile on a number of different platforms, including mac, but I don't think the mac version has even been successfully tested by anyone at all.

**Comment by CatGreen90** [comment] 2019-05-23 01:01
I can confirm that it worked for me on Sierra. It's broken on High Sierra and Mojave.
RA crash log: https://pastebin.com/QCPypHtM
macOS crash log: https://pastebin.com/VMe5XAmg

**Comment by estefan3112** [comment] 2019-11-19 21:54
Mesen 0.9.8 works for me in MacOS Mojave/Retroarch 1.8.1 (Metal) and the HD textures are just amazing. Such a great achievement. Same with Retroarch 1.8.1 for iOS.

**Comment by SourMesen** [comment] 2019-12-29 16:15
Can anybody else confirm that the builds appear to be working on Mojave/Catalina? If they do, I imagine there's been some updates on the buildbot that have fixed the builds, somehow (e.g new version of GCC/clang, maybe, etc.)

**Comment by zoharxero** [comment] 2019-12-29 18:57
> Can anybody else confirm that the builds appear to be working on Mojave/Catalina? If they do, I imagine there's been some updates on the buildbot that have fixed the builds, somehow (e.g new version of GCC/clang, maybe, etc.)

Is working for me on Mojave, Retroarch 1.8.2 (gl), tested a few games and load without problem.

**Comment by SourMesen** [comment] 2019-12-29 22:27
Thanks for the confirmation!
Closing this issue then, since it appears to be fixed.

**Closed by SourMesen** 2019-12-29 22:27 UTC
Labels: libretro
