### ISSUE TITLE
program crashes when opening audio dialog

### ISSUE THREAD

**Issue by MichaelDavid53** [SourMesen/Mesen#732] opened 2019-12-14 17:42 UTC
on linux

**Comment by MichaelDavid53** [comment] 2019-12-14 18:16
mono_crash.945d98a6d.0.json appeared in Mesen-0.9.8/bin/x64/Release 
[mono_crash.945d98a6d.0.json.txt](https://github.com/SourMesen/Mesen/files/3964158/mono_crash.945d98a6d.0.json.txt)

**Comment by SourMesen** [comment] 2019-12-14 23:35
I can't reproduce this.  What distribution are you using?

The crash is most likely a native crash, whereas that log is mono's crash log which doesn't really appear to contain any information about the crash, unfortunately (mostly contains information about the .NET runtime's state)

**Comment by MichaelDavid53** [comment] 2019-12-15 15:09
I'm still not sure what distro I'm supposed to go by...
![Screenshot from 2019-12-15 10-07-56](https://user-images.githubusercontent.com/58856153/70864725-ffd94680-1f22-11ea-8198-fca333505188.png)

**Comment by MichaelDavid53** [comment] 2019-12-15 15:55
I tried downloading the Master folder and making out of that instead. it appeared successful aside from two warnings and then after getting the program running and trying to open the audio dialog again this showed up in the terminal:

[err.txt](https://github.com/SourMesen/Mesen/files/3965112/err.txt)

**Comment by SourMesen** [comment] 2019-12-20 02:37
Thanks, this should be fixed by 8b9923135fcab65446019f2e711b89e47f702afa.

It seems like SDL can't like any audio device on your PC, which caused a crash when opening the audio settings.  I'm unsure if sound will actually work, though.

**Closed by SourMesen** 2019-12-20 02:37 UTC
Labels: bug
