### ISSUE TITLE
[Dendy] emphasis issue since 0.9.0

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#232] opened 2017-09-04 08:25 UTC
![lion king the mapper 4 unl _000](https://user-images.githubusercontent.com/13199529/30017957-c2f654aa-9163-11e7-9123-2ed8f6b2de32.png)

Lion King The (Unl)
half of screen have red emphasis instead of green

**Comment by SourMesen** [comment] 2017-09-04 12:34
Thanks for the report! This was caused by a mistake I did in my speed optimizations for 0.9.0
Only affected Dendy because it triggers NMI on a different scanline than NTSC/PAL (though using the overclocking settings probably caused the same issue)
Fixed by c79c1ffdec5b85438a3c991144e44e473c6e74da

**Closed by SourMesen** 2017-09-04 12:34 UTC
Labels: bug
