### ISSUE TITLE
TMNT 3 Chinese Translation doesn't work completely 

### ISSUE THREAD

**Issue by Koh1fds** [SourMesen/Mesen#151] opened 2017-04-29 17:02 UTC
There is some rare chinese translation romhack for TMNT 3. It's pretty interesting because it uses larger amount of CHR banks than any VRC4 / VRC2 licence games. So it properly works only in chinese Nestopia mod called Nestopia plus. Fceux and Bizhawks shows glitched graphics instead of chinese characters. In Mesen it completely crashes. Don't know if you like to make it work. Just some info. Here is an ips patch for japanese version of the game (Teenage Mutant Ninja Turtles 2 - The Manhattan Project (J) [!].nes) that converts it to chinese translation
http://s000.tinyupload.com/index.php?file_id=01126658513231411526
Also here is how that rom looks in different emulators
http://i.imgur.com/kC6U8Ei.png

**Comment by SourMesen** [comment] 2017-04-29 18:14
Thanks for the report, the crash was caused by a bug with the "trainer" support (I fixed it - 847f2bb21779af079b8f3550f5d06a99d0e0a424).  ROMs with trainers are usually very old and a good sign that they've never been tested on real hardware, though - so it's hard to tell whether this ROM actually works on a real VRC4 cart or not.  Nestopia Plus' code is not available, so I can't check what it's doing, either. With the trainer fix, the game looks identical in Mesen and FCEUX.  
I'll close this for now - I'm not really willing to spend too many hours investigating a romhack that might not even work on a real cartridge..

**Closed by SourMesen** 2017-04-29 18:14 UTC
