### ISSUE TITLE
Memory Tool ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#496] opened 2018-09-05 18:52 UTC
https://i.imgur.com/6fFvsRA.png

This error came up after loading a TBL, opening the search toolbar, and entering a number. It happens each time I enter a character or click on the < > arrows.

**Comment by torridgristle** [comment] 2018-09-05 18:52
Error stops coming up after clicking Reset TBL Mappings.

**Comment by SourMesen** [comment] 2018-09-05 23:46
I can't reproduce this exact issue, but I did find another issue when loading TBL files that have empty rules (e.g `30=`).

Looking at the code, I can't see any way for your crash to actually happen, either (although obviously I must be missing something, since it does crash on your end).  Does it happen with any TBL file, with any ROM?  Or is it only a specific ROM/TBL file that causes the issue?  Can you share the TBL file?

**Comment by torridgristle** [comment] 2018-09-06 00:14
I made another TBL with Tblater since I deleted the old one and then I used it in a different ROM, same results. https://cdn.discordapp.com/attachments/475089535563464727/487052283612495873/test.tbl

With text search disabled it doesn't give the error immediately, it just doesn't work the first few times the arrows are clicked, then the error begins popping up each time. With text search enabled it appears to be instant.

**Comment by SourMesen** [comment] 2018-09-06 00:56
Thanks - this was caused by the ```0F=...``` line in your file.  Since your TBL file is not UTF-8 encoded, this ends up being converted to U+FFFD by .NET when loading the text file.  And it's possible for an empty string to "starts with" a non-empty string when using culture-sensitive comparisons (which is odd to say the least..), which was causing the crash.

The crash is fixed by 8019e70483e080f1d607f878549f2d386230de9a, but you'll need to convert your TBL file to UTF8 if you want to display the 0F characters properly (otherwise it'll show up as a boxed ? mark).

**Closed by SourMesen** 2018-09-06 00:56 UTC
