### ISSUE TITLE
Port to macOS

### ISSUE THREAD

**Issue by CNAmira** [SourMesen/Mesen#396] opened 2018-06-03 03:07 UTC
There are three problems block it to be ported to macOS:
* `System.Windows.Forms` in macOS port is based on Carbon, but Carbon is deprecated and will likely to be removed in next version of macOS, a Cocoa version is in an early stage and not distributed in official builds of Mono. An X11 version is also available on macOS but it does NOT always perform correctly as on Linux.
* Current version of Xcode provides a modified version of LLVM+Clang, which doesn't support `std::filesystem`, next version of Xcode will support it. GCC may work but it's reported that GCC may generate garbage codes on macOS.
* Direct access to input devices is done `IOHID` framework or higher level `GameController` framework which only support Objective-C and Swift, it's quite different from the implement of Linux.
First two problems will be resolved once Mono's maintainer and Apple release compatible version, the third problem is what I'm going to be done.

**Comment by SourMesen** [comment] 2018-06-03 15:09
Nice to know that there's a new version of WinForms being worked on for macOS (the current one isn't that great, from what I have read online)

For the ```std::filesystem``` usage, it's limited to a single file and could easily be replaced with macOS-specific APIs if needed (but reverting to std::filesystem once that's available would be ideal).

For input devices, you *might* be able to use the SDL2 API, too, if that's any simpler.  Keep in mind that the Linux version doesn't use SDL2 for the input because I never managed to make it work - there is something about Mesen that SDL2 doesn't like (I think it's caused by the fact that the main window is managed by Mono - if I let SDL2 create its own window, the SDL input code worked properly)

Either way, I'm more than happy to merge anything that gets us closer to having macOS support.

**Comment by CNAmira** [comment] 2018-06-04 20:34
The Xcode 10 beta released right now does support `std::filesystem`. The only problem is WinForms is quiet broken and new WinForms implement is still in development.

**Comment by SourMesen** [comment] 2018-06-07 04:28
Yea, everything I read online about WinForms on macOS said it wasn't very solid, hopefully the new one fixes most of the issues - the Linux one work pretty decently, aside a few performance issues & some minor glitches that can be worked around.

**Comment by SourMesen** [comment] 2018-08-27 23:40
Closing this for now since this will likely not be solved soon (and there isn't too much I can do on my end at the moment in terms of Mono macOS support).

Based on my experiments, though, it will probably be easier to get Mesen to run under Wine than under Mono, unless the new macOS backend of WinForms is far better than the current one (which is excessively broken from my testing).  Mesen on Wine works, but the debugger has some performance issues that I will need to investigate to see if I can work around them.  I will probably not have the time to do this anytime soon, though.

**Closed by SourMesen** 2018-08-27 23:40 UTC
