### ISSUE TITLE
Life Force / Salamander Overclock Issue

### ISSUE THREAD

**Issue by Koh1fds** [SourMesen/Mesen#162] opened 2017-05-14 22:53 UTC
I tested only 480 extra scanlines. Sorry. I test it with 0.90 version of mesen with Famiclone sound fix. It happens on 0.90 without sound fix also.

For some reason if you use overclock then game glitches a little bit before boss battles. Seems like boss music starts earlier than usual for some reasons and maybe that causes glitches. This doesn't happen in version 0.81 and in fceux.

**Comment by SourMesen** [comment] 2017-05-14 23:34
Thanks, I'll take a look - not sure if there is anything left that's different between Mesen's and FCEUX's implementation for overclocking, though.
Are you testing this in NTSC or Dendy mode?

**Comment by Koh1fds** [comment] 2017-05-15 00:39
I tested it in NTSC mod

**Comment by SourMesen** [comment] 2017-07-16 00:03
Sorry for the wait!  This should be fixed by 80581e61185318cfc0315b03354ce581b4f2dff9. It was caused by a small change I made in 0.9.0 to support Bizhawk's movies.

**Closed by SourMesen** 2017-07-16 00:03 UTC

**Comment by Koh1fds** [comment] 2017-07-16 18:57
Thanks! Can't wait for update. I also really want to test that new option for "no sprite limit" or something.
I was trying to build last update by myself, but i can't do it.

**Comment by SourMesen** [comment] 2017-07-16 19:20
I made a temporary build with the fixes if you want to try it: https://www.mesen.ca/MesenOverclockFix.zip  
The no sprite limit option is just to prevent some issues with the "no sprite limit" option that can occur in some games (e.g Zelda 1 in the doorways in dungeons)

**Comment by Koh1fds** [comment] 2017-07-16 21:30
>The no sprite limit option is just to prevent some issues with the "no sprite limit" option that can occur in some games (e.g Zelda 1 in the doorways in dungeons)
This is exactly what i want. I was asking about it here:
http://tasvideos.org/forum/viewtopic.php?t=18447
