### ISSUE TITLE
Camstudio (CSCD) Video Bug

### ISSUE THREAD

**Issue by Cibomatto2002** [SourMesen/Mesen#149] opened 2017-04-27 07:02 UTC
When trying to make a video with Camstudio (CSCD) you see strange colors and other bugs going on. Here is a video.

https://sendvid.com/t92ese8e

**Comment by SourMesen** [comment] 2017-04-27 13:32
I'm not seeing any problem on my end. Have you tried updating your codec pack?
Also, sending me the actual video file you recorded would let me confirm if the problem is your computer or the video.

**Comment by Cibomatto2002** [comment] 2017-04-27 18:10
I have K-Lite Codec Pack Standard Version 13.1.0 ~ April 14th 2017 installed. https://www.codecguide.com/download_k-lite_codec_pack_standard.htm

Here is the Video. http://www.mediafire.com/file/c9dz91fl3fxpd53/Jackal_%28USA%29.avi

**Comment by SourMesen** [comment] 2017-04-27 20:15
Thanks - it looks like the problem is caused by the fact that the movie's height isn't a multiple of 4, most likely because of your overscan settings - it shouldn't be too hard to fix.

**Comment by SourMesen** [comment] 2017-04-27 21:47
This should be fixed by 8a2f09b0fd38566f9e234206145aa86bc7452e6b

**Closed by SourMesen** 2017-04-27 21:47 UTC
