### ISSUE TITLE
Video Size Issue

### ISSUE THREAD

**Issue by buvk** [SourMesen/Mesen#65] opened 2016-11-17 00:29 UTC
In order to use integer scaling in fullscreen, you need to go fullsreen first, then set the video size.  If you set video size before going fullscreen, the setting is lost when you go fullscreen.

If you are using a specific video size when in fullscreen, leaving fullscreen causes the video size setting to be lost.

**Comment by SourMesen** [comment] 2016-12-09 17:09
Thanks for the report!
Setting the scale to "fullscreen" when opening up fullscreen is by design, and it is probably what most users expect.  Otherwise most users would be forced to turn on fullscreen mode and then turn on "fullscreen picture", which could be relatively annoying.  Is there a reason changing the scale manually (i.e by using the alt-1 to alt-6 shortcuts) when turning on fullscreen mode is a problem for you?

**Comment by SourMesen** [comment] 2016-12-24 21:33
The bug you reported where switching back to window mode after setting a specific video size would cause the selected scale to be ignored was fixed a little while ago.
I'm closing this issue for now since I don't know what else could be done to improve your use case without making fullscreen mode harder to use for others - feel free to comment and give ideas if you have any!

**Closed by SourMesen** 2016-12-24 21:33 UTC
