### ISSUE TITLE
2nd Player Controller Map Saving Issue

### ISSUE THREAD

**Issue by jillsandwicher** [SourMesen/Mesen#358] opened 2018-04-05 16:53 UTC
I was using 0.9.3 without a hitch.  Downloaded 0.9.5 and the 2nd Player Controller Settings refused to save on exit/relaunches.  Tested using both xinput (DS3 with SCPtoolkit) and keyboard binds. Right clicking the exe and ticking "Run this program as an administrator" fixed the issue however.  Even though it's technically working now, I am opening this issue so it can be looked into and fixed in the later versions so you don't have to grant administrator rights every time an update is done.  Also since 0.9.3 didn't require it, I wonder what and if there are other settings that aren't properly saving if you don't grant the rights beforehand.

Win 7 Ultimate 64-bit OS

**Comment by SourMesen** [comment] 2018-04-06 02:33
Thanks for the report.  

It's likely that this was some sort of upgrade glitch going from 0.9.3 to 0.9.5, especially since 0.9.4 contained a ton of input-related changes.  I've seen similar issues on my end a number of times, but usually after running an older version of Mesen after the config file had already been updated to a newer release (which isn't really supported).  I tried performing a simple upgrade from 0.9.3 to 0.9.5 and couldn't reproduce the issue, though.

All config options are saved to the same settings.xml file in Mesen's data folder - so there is no reason why admin rights would ever be required (unless the file itself was made to be read-only without admin rights).  It's possible you performed slightly different steps when you opened it as an admin, which allowed it to save the settings.xml file properly (and most likely make the error go away permanently)

**Comment by jillsandwicher** [comment] 2018-04-06 15:45
Thanks for the feedback.

I've ran a few more tests.   And I think the problem was I was closing Mesen and reopening it way too quickly.  Giving it a few more seconds to save and write properly on exit seemed to do the trick though I can't be certain that is the exact reason for my non-saving instances.

**Comment by SourMesen** [comment] 2018-07-03 02:47
I had to setup keys a few times today and I ended up finding a bug that caused all changes to be lost in the input form.  There's a good chance this was the source of the configuration issues you had - if so, it should be fixed in the next release (fixed by e1da06fe04dfe24f567bc63acb7e85d80a3c0fb4)

**Closed by SourMesen** 2018-07-03 02:47 UTC
Labels: bug
