### ISSUE TITLE
Debugger tools / speed up eventually resulting in PC slowdown

### ISSUE THREAD

**Issue by jeffkontak** [SourMesen/Mesen#812] opened 2020-04-27 11:10 UTC
Since upgrading recently to a powerful new Windows 10 PC, I've occasionally had my computer gradually slow down to the point of being unusable while running Mesen, particularly while using debugging tools or running games at 9X speed. Nothing ends up showing up as a problem when I investigate PC performance. A full restart totally clears the issue.

**Comment by SourMesen** [comment] 2020-04-27 21:18
How many debug tools are you opening at once?
If you're opening several ppu viewers, event viewer, hex editor, etc. all at once, and have them all set to high refresh rate, sometimes the UI ends up being stuck in a permanent loop where it processes the requests to redraw/update the tools, and by the time it's done, there are already more pending messages to redraw/update the tools again.  This loop ends up preventing clicks/buttons/etc work being responsive and effectively lock up the UI.

I've actually implemented a bit more logic in Mesen-S to try to reduce the odds of this ever happening, but I think I might have not ported those changes over to Mesen, which might be a (partial) solution to this

**Comment by jeffkontak** [comment] 2020-04-27 21:34
Thanks for reaching out about this. This has happened three times so far. The first time it happened, I wasn’t using any debugger tools. I was only doing 9x speed while playing Dragon Warrior. For the second and third occasions, I probably had one instance of the PPU viewer open. For one of those occasions, I was using the Trace Logger with the PPU viewer opened. No multiple instances.   Overall the issue has been infrequent enough to not dissuade me from taking advantage of all the things I love about Mesen. Let me know if I can answer anything else. Sent from Mail for Windows 10 From: SourMesenSent: Monday, April 27, 2020 5:18 PMTo: SourMesen/MesenCc: jeffkontak; AuthorSubject: Re: [SourMesen/Mesen] Debugger tools / speed up eventually resulting in PC slowdown (#812) How many debug tools are you opening at once?If you're opening several ppu viewers, event viewer, hex editor, etc. all at once, and have them all set to high refresh rate, sometimes the UI ends up being stuck in a permanent loop where it processes the requests to redraw/update the tools, and by the time it's done, there are already more pending messages to redraw/update the tools again. This loop ends up preventing clicks/buttons/etc work being responsive and effectively lock up the UI.I've actually implemented a bit more logic in Mesen-S to try to reduce the odds of this ever happening, but I think I might have not ported those changes over to Mesen, which might be a (partial) solution to this—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jeffkontak** [comment] 2020-05-07 10:34
I wanted to u update you. I just had my first instance of this extreme computer slowdown and eventually freeze occurring when I wasn’t running Mesen. (Let’s be honest, I’ve been using a lot of Mesen.) Therefore, it would seem that the issue has nothing to do with your software. Sent from Mail for Windows 10 From: SourMesenSent: Monday, April 27, 2020 5:18 PMTo: SourMesen/MesenCc: jeffkontak; AuthorSubject: Re: [SourMesen/Mesen] Debugger tools / speed up eventually resulting in PC slowdown (#812) How many debug tools are you opening at once?If you're opening several ppu viewers, event viewer, hex editor, etc. all at once, and have them all set to high refresh rate, sometimes the UI ends up being stuck in a permanent loop where it processes the requests to redraw/update the tools, and by the time it's done, there are already more pending messages to redraw/update the tools again. This loop ends up preventing clicks/buttons/etc work being responsive and effectively lock up the UI.I've actually implemented a bit more logic in Mesen-S to try to reduce the odds of this ever happening, but I think I might have not ported those changes over to Mesen, which might be a (partial) solution to this—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SourMesen** [comment] 2020-05-08 01:15
Ah, good to know.  So for now I'll assume Mesen isn't the cause and close this - thanks for letting me know!

**Closed by SourMesen** 2020-05-08 01:15 UTC
Labels: invalid
