### ISSUE TITLE
Audio pops in every game

### ISSUE THREAD

**Issue by ghost** [SourMesen/Mesen#539] opened 2018-12-04 18:18 UTC
I've been having audio issues in Mesen on every rom I've used. Every 5-10 seconds or so, the audio "pops". I've tried adjusting settings to see if that helped to no avail. Recorded video & audio do not have this issue.

**Comment by SourMesen** [comment] 2018-12-04 23:12
The only settings that should affect this are the "Latency" and the "Disable dynamic sample rate" options in the audio options.  
If you've tried setting the latency to a high value (e.g 100+) and it still causes popping, there is probably something about your system that doesn't agree with Mesen's audio code.  In that case, I will probably not be able to help much - all 4 computers I have access to do not have any issues with the sound (I've tested this extensively a few months ago), so it makes it rather hard to debug this kind of problem.

What OS are you running?
In the shortcut keys in the preferences, there's a shortcut named "Toggle Debug Information".  Bind this to a key and use it, it will display some real-time debug info about audio and video which might help understand the problem.

**Comment by coron13** [comment] 2018-12-05 10:19
Thank you for replying. I've tried using different values for latency, such as 150, 200 and 250, and I've tried "Disable dynamic sample rate", but it doesn't change anything. 

Using the debug overlay, I can see I have 0 underruns after 5 minutes of checking. I'm not really sure what information you could use from the debug overlay. The audio latency goes into red numbers very often, both lower and higher values.

I'll attach a picture showing the debug overlay after running for about 5 minutes, with a latency value of 200. I'm running Windows 10 Pro 64-bit Build 1809.

![image](https://user-images.githubusercontent.com/36478582/49506875-858dd500-f87f-11e8-8187-0e67518b2717.png)

**Comment by Cibomatto2002** [comment] 2018-12-06 05:57
Have you tried other NES Emulators to see if you have the same problem?  I had this trouble on FCEUX Emulator.

**Comment by coron13** [comment] 2018-12-06 13:34
Good idea. I have tried Nestopia, FCEUX, Jnes, Mednafen and puNES. None of them have any audio issues with my system.

While I don't know anything about programming and such, I suspect it's a video or audio sync issue, since recorded files form Mesen sounds perfectly fine. I do not have vertical sync enabled.

**Comment by coron13** [comment] 2018-12-09 22:35
The video frames delays varies a bit, both when running for the first time, and after power cycling. My picture from before might be misleading, as I'm running a translated FDS game, if that changes anything. 
The following picture is a clean normal ROM after running for 6 minutes:
![image](https://user-images.githubusercontent.com/36478582/49703870-dd736580-fc0a-11e8-8350-1beb5a1cb41e.png)

I'm running on a desktop with an Intel Core i5-6600K, Geforce GTX 1070 and 16 GB DDR4 RAM. Turning off Game Mode changed nothing as far as I can tell (or at least, the sound popping is still there). 

I've actually had this audio issue for some time. If I had to guess, it appeared since the april update for Windows 10, so like you say, Windows 10 has a few bugs (I had the disappearing files bug from the October update too).

**Comment by Cibomatto2002** [comment] 2018-12-10 06:04
Try a older Copy of Mesen maybe it will help. 

https://ci.appveyor.com/project/Sour/mesen/history

**Comment by coron13** [comment] 2018-12-10 13:58
Tried many older versions, the oldest being 0.5.3, but it didn't change anything.

Don't know if this helps, but the popping is still there when no audio is playing, like on the title screen for Wrecking Crew for example.

**Comment by coron13** [comment] 2018-12-10 18:43
It is very odd that it only affects Mesen. I run many different emulators on my PC, but only Mesen has this popping sound. Sounds like either Windows 10 have screwed with a part Mesen uses for sound that other emulators don't use, or my headphones' driver is unusual. Must be the latter, since as far as I can tell I'm the only one to have this problem. For reference, I'm using the Logitech H800 headset.

**Comment by SourMesen** [comment] 2018-12-12 23:51
Do you get the same popping issue with the laptop's built-in speakers? (I'd imagine you would, but you never know..)

Mesen just uses DirectSound in a very basic way for audio on Windows.  DirectSound itself is ancient, but still used by a ton of software, afaik.

**Comment by coron13** [comment] 2018-12-13 11:32
I tried using normal jack-stick headphones on my desktop, and the popping is gone. It seems the problem is with my Logitech headset. Its wireless and uses a USB reciever, so maybe the problem lies there.

I'm using DirectSound on BSNES without any problems.

**Comment by SourMesen** [comment] 2018-12-15 17:37
That's definitely odd - there's no real reason why Mesen's sound output should be any different between a pair of headphones and another (there is no device-specific code in Mesen).  That said, I don't think I can really fix this either, as it is.

**Comment by Cibomatto2002** [comment] 2018-12-16 07:34
Maybe you need to update the drivers.

**Comment by coron13** [comment] 2018-12-16 13:54
Well, my headset doesn't use any specific drivers. There was some assistant software, which didn't change anything after installing. 

Thanks so much for helping me. I'll just use other emulators until I get a new headset, maybe that changes things.

**Comment by SourMesen** [comment] 2018-12-18 04:33
Initially, you said "every 5-10 seconds", could you check if this is consistent?  If it's consistently every 5 seconds or every 10 seconds, there might be something that Mesen is doing periodically that might be causing this.   e.g, for example, every 5 seconds Mesen tries to update the list of plugged in controllers (both XInput & DirectInput) to see if any new controllers have been plugged in, it's unlikely but not impossible that this might have an impact on this particular headset.

If the delay between the glitches varies (e.g sometimes it's 4 secs, sometimes 12 secs, etc.) then I'm mostly starting to be completely out of ideas. :p

**Comment by coron13** [comment] 2018-12-18 13:22
I tried testing using a stopwatch app on my phone. It seems very consistent. About every 4.5 seconds popping occurs.

**Comment by SourMesen** [comment] 2018-12-18 21:32
Try this build out: https://www.mesen.ca/MesenTest.zip
I've disabled the controller-related code that runs every 5 seconds (the one I mentioned yesterday), maybe it'll help?  If it doesn't though, I'm out of ideas unfortunately.

**Comment by coron13** [comment] 2018-12-19 11:46
That works! Popping is entirely gone. Audio is completely perfect.
Thanks so much!

**Comment by SourMesen** [comment] 2018-12-19 22:30
Cool - that at least confirms what the source of the problem was.  Now the problem is how to actually fix it without disabling that feature altogether.
Either way, feel free to keep using that build for now - I'll try to figure out a proper way to fix this before the next release.

**Comment by coron13** [comment] 2018-12-19 23:17
That sounds great!
Mesen is the best NES emulator, so I appreciate all of this. Filled to the brim with options and tools.

**Comment by SourMesen** [comment] 2019-01-20 18:47
I *think* this should be fixed as of the latest appveyor build.  Was hoping to get ask you to test the fix, but since it looks like your GitHub account's been deleted, I guess I'll just have to hope it's fixed properly.

If you (or anyone else) still get the problem in the latest dev build, please let me know.

**Closed by SourMesen** 2019-01-20 18:47 UTC
Labels: bug
