### ISSUE TITLE
Sound is still not that accurate

### ISSUE THREAD

**Issue by tildearrow** [SourMesen/Mesen#567] opened 2019-01-25 04:03 UTC
Although the tests claim test_apu_sweep to be passing, I do not think that is the case.

NES recording at 0.25x speed with metronome: https://instaud.io/3dwJ

Mesen recording at 0.25x speed with metronome: https://instaud.io/3dwK

In case you were unable to hear the difference, here are some slowed down recordings:

Part of NES recording at 0.03125x speed with metronome: https://instaud.io/3dwL

Part of Mesen recording at 0.03125x speed with metronome: https://instaud.io/3dwN

As you can hear, the timings in Mesen are not accurate.

**Comment by SourMesen** [comment] 2019-01-25 04:31
Thanks for the report.  I'm not quite sure what these recordings are from, however. Neither of the 2 tests from the test_apu_sweep folder I have seem to sound anything like this recording, at the very least.

Is this a test you've built or found somewhere? If so, having the actual ROM would be needed - I can't fix anything based on a recording alone.

**Comment by tildearrow** [comment] 2019-01-25 04:33
It is a test that appears in the "Accuracy Tests" in the website (https://www.mesen.ca/#Accuracy).

The test can be found here: https://forums.nesdev.com/viewtopic.php?t=219

**Comment by SourMesen** [comment] 2019-01-25 05:46
Thank you very much for the report!
This was actually an ancient bug caused by the way the emulation "catches up" the APU after a while, rather than emulating it cycle by cycle (to improve performance).
This caused an issue in the frame counter's pacing, which is why the delay between each sweep unit frequency change was not consistent.

I have a working fix, but needs a bit more testing - should be fixed tomorrow.

**Comment by SourMesen** [comment] 2019-01-26 01:59
This is fixed as of bf86f5458ac6be23c9290f8e10069a4e0123bd61.

I compared your recording (middle) with Mesen's before (top) and after the fix (bottom) in Audacity:
![image](https://user-images.githubusercontent.com/21093973/51781216-a9cd9b80-20e3-11e9-98e7-d47687661d2b.png)

You can clearly see in the top section that the timing for the sweep unit ticks were all off by a small (random-ish) margin.

Thanks again for the report - I would never have noticed this myself!

**Closed by SourMesen** 2019-01-26 01:59 UTC
Labels: bug
