### ISSUE TITLE
mese crashes regularly when save state is loaded while memory editor is open

### ISSUE THREAD

**Issue by tehmugi** [SourMesen/Mesen#500] opened 2018-09-07 15:20 UTC
more or less as the title says.
it doesnt always happen, but when it does, it always manages to do it in a point where it makes me lose all my work and completely flip a table.
I havent noticed a connection between whether or not anything has been edited in memory editor, simply having it open seems to be enough to just tilt it.

not super urgent or important I suppose but figured i'll let you know regardless. 
(mesen v0.9.6 / win7 64bit in-case this is of relevance.)

**Comment by SourMesen** [comment] 2018-09-07 20:36
Thanks for the report.

Does this happen with any game or have you only gotten it with a specific one?  Can you easily make it crash if you keep spamming the load state buttons?  I'm taking a guess and assuming the memory tools were displaying the contents of CPU memory?

That being said, it's definitely possible for it to crash in rare circumstances because that particular code is not really thread-safe.  I can most likely fix it without being able to reproduce it, but if possible I'd prefer being able to reproduce it on my end to test the fix.

**Comment by Kitsu-neechan** [comment] 2018-09-07 21:59
I've only had this happen with shatterhand. (working on a hdpack) which is the only nes rom i've ever messed with (im not much of an emulator person.)

I havent really tried to spam it to crash but will do as soon as i get time to, though from what i've observed, it appears to more likely do it when i leave the emulator and the memory editor open for extended periods of time (i keep it paused while i update my hires.txt for up to 10 hours a day)

one other thing i did notice which im not sure if related or not, but it appears that the rate at which it crashes is exponentially going up if you attempt to "record" a HDpack while the memory editor is open.

**Comment by SourMesen** [comment] 2018-09-07 23:05
I still haven't had any luck trying to reproduce the crash, unfortunately.
The next time you get the crash with 0.9.6, could you take a memory dump of Mesen.exe using the task manager before you close it and then send the .dmp file my way?  That should hopefully let me get a better idea of what's causing the crash.

**Comment by Kitsu-neechan** [comment] 2018-09-07 23:30
i can try, but generally it just closes itself. mostly when it happens, the sound is just stuck playing the same sample for a second or 2 and then it either just closes or gives the "application is not responding" window... mostly the former.

**Comment by SourMesen** [comment] 2018-09-08 01:46
Thanks - f69b891d5317a28a7712d35ac9296e472e2bc64c should hopefully fix most of the issues that occur when recording HD packs while any debugging tool is opened.

FYI, while the "This application has crashed" dialog is shown (after the Mesen window gets closed), the Mesen process should still be visible in the task manager so long as you don't press close on that window.  You should be able to take a dump even after the process crashes that way.

You can try the latest appveyor build to see if you still get crashes with it (once it's available - looks like Appveyor might be having some technical issues at the moment).  If you do get crashes though, I won't be able to analyze the crash dumps from the appveyor builds (its needs to be a crash dump from the 0.9.6 release build for me to be able to load it properly on my end)

--

Unrelated, but I noticed the hd pack builder's performance was a lot worse than I recalled, so I checked and fixed an obvious bottleneck in the code (fd33562205732b3ef14ff9ca4cb61d0312f61a54).  This more than doubled max FPS on my end (and hopefully means that most people should now be able to get a stable 60 FPS while recording)

**Comment by Kitsu-neechan** [comment] 2018-09-08 09:38
i will definitely give it a go, since i do my hdpack recording in tiny pieces and constantly forget memory editor open when doing so, this was a pretty usual way for me to get annoyed by having to setup everything again whenever it tilted for me.

on a semi related note: i noticed that if you start recording a hdpack while one is already in use, the game graphics will revert back to that of the original rom, while the emulator still does indeed record from the hdpack that was in use. I use this technique in shatterhand to identify undumped dublicate tiles and other not dumped graphics that usually appear only under specific conditions and take extended effort to get to.

is there a technical reason for why the emulator stops displaying the hdpack's graphics during a record ?

**Comment by SourMesen** [comment] 2018-09-08 17:32
It's mostly a matter of code simplicity/performance.  

It's not technically impossible to have the HD version show up while recording, but it would require a fair amount of changes to be done to the code used to record HD packs.  It might also be a performance concern on some low end PCs, so if I were to change this it would need to be an option.

**Comment by Kitsu-neechan** [comment] 2018-09-08 20:03
It was more of a curiosity than a feature request, though i do think it would benefit people working packs on games like shatterhand im working on, where some things reallly require extra effort to be put into getting specific tiles to record. 
Shatterhand for example likes to duplicate its tiles based on certain conditions like the frames of the main character sprite. Since the hdpack is disabled during recording, i didn't see for example, which duplicates of the robot suit attack projectile were already textured while recapturing, and to capture an obscure double firing while jumping sprite, it took me more than half a hour of blind recording to finally catch it.

**Comment by SourMesen** [comment] 2018-09-09 01:28
Would showing statistics in the HD pack recorder window be useful, then?
e.g: number of tiles recorded (+ the delta vs the start of the recording), the time at which the last tile was recorded, etc?  This would at least allow you to know whether or not you've managed to capture new tiles.

**Comment by Kitsu-neechan** [comment] 2018-09-09 14:26
It could be but im not sure how that would work in practice.
Generally i null the hdpack when i start re-recording, simply because when tile grouping is used, re-recording over an existing hdpack can have some really nasty effects on the existing tile sheets.
im also not using the tilesheets generated by the hdpack builder on the final build of my pack either, instead i have crafted each sprite sheet by hand and the currently 12000 lines holding hires.txt is entirely handwritten, documenting the purpose of every section and tile set of it. (it's slightly OCD but in games like shatterhand, the autogenerated tilesheets are so messed up they're practically unusable, not to mention that they repeat sprites up to 25 times per tile.)

if it would track the number of unique tiles recorded per game (hash based i suppose) and wouldn't mind having the hdpack purged in-between it could work. Sounds a little complicated to execute though... but what do i know :P

**Comment by SourMesen** [comment] 2018-09-13 00:50
Turns out that allowing hd tiles to continue to show while recording was pretty easy to implement code-wise, I'll try to commit the change sometime tomorrow.  It does have a slight impact on recording performance (~10-15% slower), but that's easily solved by disabling hd packs in the video options before recording.

Have you gotten any crashes with the appveyor builds so far? (if you've tried them)

**Comment by Kitsu-neechan** [comment] 2018-09-13 09:06
That's neat, i know for sure that having it active during record will definitely make my life easier.
The performance drop shouldn't really be an issue tbh, atleast for me, when i record, i hardly play the game "properly" insdead i do it little by little so having absolutely flawless performance during it is not exactly a requirement (for me atleast.)

Havent tried the new builds yet, im either blind, or just stupid but i couldn't for the life of me figure out where to actually download those :P (i will just pull the source and build it myself soonish.)

**Comment by SourMesen** [comment] 2018-09-13 11:15
The download page for appveyor builds is here: https://ci.appveyor.com/project/Sour/Mesen/build/artifacts

Direct link to the latest build: https://ci.appveyor.com/api/buildjobs/vnbhgjwg0atcgb3v/artifacts/MesenDevWin-0.9.6.33.exe

**Comment by SourMesen** [comment] 2018-09-14 02:16
And this one should let you see the HD graphics while recording: https://ci.appveyor.com/api/buildjobs/4ny4ujc134jig9sc/artifacts/MesenDevWin-0.9.6.34.exe

**Comment by Kitsu-neechan** [comment] 2018-09-14 09:49
Wonderful. I tried it out and it certainly makes my life less crash-prone. no longer memory editor related crashes so far, and while you did say that the performance was affected, i had memory editor running with high refresh rate (cpu hog) and doing a hd pack recording but it barely dips below 60fps at all. 

only thing i did notice was that while i was doing a record with memory editor open , the pause symbol keeps flashing on the top left corner of the emulator. This happened on the old 0.9.6 too but it wasn't really an issue because having the memory editor open would always crash the emu, since it now doesnt, maybe that should get fixed :P

**Comment by Kitsu-neechan** [comment] 2018-09-15 10:05
so far so good atleast. though i've only used it for one day now, but yeah, i will just create a new bug report if i run into something interesting again. so feel free to close this one.

thank you for the implementations here, they really make my life easier :)

**Closed as completed** 2018-09-15 13:22 UTC
Labels: bug
