### ISSUE TITLE
libretro test

### ISSUE THREAD

**Issue by eugene-s-nesdev** [SourMesen/Mesen#300] opened 2018-01-06 00:19 UTC
Hi, Sour
Thank you for great libretro core.

I have some suggestions
- Need to do shorter text in core options (i.e "composite-direct-fbx" instead of "Composite Direct by Firebrand X") because RGUI interface is low-res
- can you add 4:3 to the aspect ratio (Auto, NoStretch, NTSC, PAL, 4:3)
- I've tested mesen_libetro.x64.dll (https://www.mesen.ca/MesenLibretro.zip) on Win7x64
but INPUT doesnt work at all

**Comment by SourMesen** [comment] 2018-01-06 00:24
Hey,

4:3/16:9 were actually in there at first, but I removed them because RetroArch itself offers them automatically.  I can put them back in though.

There's a bug at the moment, the input doesn't work for any games that are not in Mesen's game database (the emulator doesn't connect any controller to the NES core).  So if you're testing with roms that say "Game not found in database" in the log window in the standalone version, this is probably normal.

**Comment by eugene-s-nesdev** [comment] 2018-01-06 00:29
Put back it please, 4:3 is very useful for nes, fceumm and nestopia cores have it too.
- Need to do shorter text in core options (i.e "composite-direct-fbx" instead of "Composite Direct by Firebrand X") because RGUI interface is low-res

**Comment by retro-wertz** [comment] 2018-01-06 00:35
its a bit an inconvenience to use retroarch's aspect ratio as this affects
all cores/and/or meses with configs. an individual core option for a 4:3 tv
aspect would be better just like most cores have. of course, this is left
for designer to decide.

**Comment by eugene-s-nesdev** [comment] 2018-01-06 00:41
https://forums.libretro.com/t/mesen-core/14124
> Performance-wise, it is most likely much slower than both FCEUmm & Nestopia UE - I would be surprised 
> if this was able to run at full speed on a Rasberry Pi, for example (but you never know).
I can do test on RPI3, bui if anyone can compile this core for armhf

**Comment by SourMesen** [comment] 2018-01-06 00:52
I'll add the 4:3/16:9 ratios again when I get the chance.  And see about shortening the palette names.

The "smooth" palette I am not sure, did not know it existed.  Firebrandx renamed some of his palettes a few times, so it might be in there under an older name, or it might be missing completely - I'll check.

About RPI3, we'll have to see if we can manage to get this building on the libretro's buildbot first, I think.

**Comment by retro-wertz** [comment] 2018-01-06 00:54
Firebrandx has updated his palette files. Smooth is whats his latest work, other are removed. his site should list them..

on that note a new wavebeam palette is also in the works,and firebrandz is has also a part in modding that. maybe it can be added too. keep the rest of custom pal as external.

**Comment by eugene-s-nesdev** [comment] 2018-01-06 01:01
Input works only with original ROMs (with no trainers or translated),
but input buttons are messed up

Default must be

Z = "B"
X = "Turbo A"
A = "B"
S  = "Turbo B"

Mesen have:

Z = "A"
X = "A"
A = "Turbo B"
S  = "Turbo A"

**Comment by SourMesen** [comment] 2018-01-06 01:03
Yes, that's the bug I mentioned - it's a simple fix.
The defaults I used were what seemed to match my Xbox 360 controller without remapping anything at all, though.  I'll double check - I know they don't match nestopia's layout, though.

**Comment by retro-wertz** [comment] 2018-01-06 01:07
no, keep that mapping(i usually play in that layout, easier to switch between turbo mode, and non turbo if needed withot awkward hand position). make it a core option instead for this layout and the usual NES layout.

**Comment by Awakened0** [comment] 2018-01-06 01:19
The audio volume is quite low, like someone mentioned on the Libretro forums. Even if I pump up RetroArch's audio volume option to it's highest (12.0) it's not as loud as the default 0.0 in Nestopia.

Excellent work on this, BTW :)

**Comment by eugene-s-nesdev** [comment] 2018-01-06 01:56
FDS issue:
Default retroarch setting is
Q (L stick) - switch disk
W (R Stick) - insert/eject disk

But "W" is reset game in mesen core

**Comment by SourMesen** [comment] 2018-01-06 02:05
Weird that the volume seems so low for some people, I haven't really noticed it being all that low while testing.  I'll check again.

W is reset?  I didn't actually do anything to map a reset button, as far as I know, though?

**Comment by eugene-s-nesdev** [comment] 2018-01-06 02:16
I dont know root of this issue, but seems in mesen "W" are eject disk (no eject/insert) and reset game same time

**Comment by eugene-s-nesdev** [comment] 2018-01-06 02:24
![symb](https://user-images.githubusercontent.com/13199529/34635504-abde3644-f2a1-11e7-9fd7-f5e3504edd22.png)

Degree symbol are wrong in RGUI (im sure its RGUI problem)

**Comment by SourMesen** [comment] 2018-01-06 16:17
FYI, I fixed the sound volume, added 4:3/16:9 ratios, fixed the input bug with games not in the game database and changed the degree symbol for "degrees" instead to avoid that display issue.

Still leaves a couple of issues, but it's a start :p

**Comment by eugene-s-nesdev** [comment] 2018-01-06 16:31
Thank you, i'll wait for libretro buildbot dlls.
Messed up input mapping is unfixed yet, i guess

**Comment by SourMesen** [comment] 2018-01-06 19:39
The cores are available on the libretro buildbot, including the Linux ARM core for Lakka, so you could give that a try.  I don't expect it to be able to run at full speed, though, but you never know!

**Comment by rzumer** [comment] 2018-01-08 01:42
In 0.9.4, resetting through RetroArch seems to "crash" to a black screen, so the only way to reset is to close and restart manually. I don't know if this is also an issue in the standalone version.

**Comment by SourMesen** [comment] 2018-01-08 04:38
The reset bug when trying to change FDS disks should be fixed by efe60a082e62c00d85c55c5aba58fc9cb38e9b62 (along with a couple more issues with shortcuts)

**Comment by eugene-s-nesdev** [comment] 2018-01-08 16:12
Hi, Sour. 
There are trange performance issues both with D3D and GL drivers.
System:
Core i7-2600K@3.4GHz (default) / Intel HD3000 / 16Gb DDR3 / Win7x64:

Here is test:
https://youtu.be/U2_VGzUy-zE

Sorry for 360p, youtube convert 1080p MTS incorrectly.
No way for bandicam or another capture software, because it drops performance.

BTW, mesen core crashes sometimes when you'll try load state (F4)
Check it on your system please.

**Comment by emu-russia** [comment] 2018-01-08 16:38
P.S. Standalone mesen, fceumm_libretro and nestopia_libretro
have enough performance to run on 16x multiplier.
mesen_libretro is slow, even 38x not enough.
![test](https://user-images.githubusercontent.com/3542018/34680981-8ec8dcba-f4ab-11e7-97ac-ef2ce0d93eeb.png)

**Comment by MattiHameister** [comment] 2018-01-08 20:57
Hi. Thanks for your work. :)

RetroArch-Shaders don't seem to work? I tried crt-interlaced-haliation and it results in a blurry image. If I try crt-royale the performance is extremly slow. They work fine with the nestopia core. Maybe a wrong resolution is used?

**Comment by Awakened0** [comment] 2018-01-08 21:09
I've been using crt-easymode-halation with it and it works just as well as it does with Nestopia. I'm using the GLSL version.

I also haven't noticed performance issues with the core on Windows 10 with a 2500k at 4.4ghz. I get full speed, no sound crackles with hard sync enabled, hard sync frames 0 and frame delay 4 (latency reducing options that are CPU intensive). I can do frame delay 8 on Nestopia (the higher you set that the more latency is reduced, but higher is harder on the CPU), but I expected Mesen to be a little heavier on my CPU.

**Comment by SourMesen** [comment] 2018-01-09 01:48
Thanks for testing!  I think I found the source of the performance issue - I had hardcoded the "internal" resolution to be 2560x2400 to be able to support up to 10x size hd packs without resetting the video subsystem, etc.  But it turns out that doing so eats up a large about of GPU memory, and probably has an impact on performance on lower-end GPUs (my GTX 1070 doesn't seem to care too much about it, even at 30x resolution, though).

I've changed this to alter the resolution as needed when options change, instead.  So it should use up a lot less GPU RAM, and hopefully this will fix the performance issues, as well as the issues regarding shaders.  A build with the changes should show up on the buildbot in the next few hours.

I also tried loading tons of save states from a few different games, but wasn't able to get it to crash.  Is it possible that the save states you were trying to load were taken from a previous build of the core?  I did something related to save states yesterday to fix netplay in retroarch.  If you have any specific save state that seems to be causing this often, attach it here and I'll try it out on my end.

**Comment by eugene-s-nesdev** [comment] 2018-01-09 05:54
Updated mesen core. Just tested it on working machine:
-Pentium G4500 (Skylake-S) 3500Mhz, 2C/2T
-Intel HD Graphics 530
-Win10

It work flawlessly.
So, i need test it on i7-2600K (SandyBridge) / IntelHD3000 again.

**Comment by MattiHameister** [comment] 2018-01-09 13:05
I can confirm that the shader issue is fixed now. Thank you.

**Comment by eugene-s-nesdev** [comment] 2018-01-09 14:58
Retested on i7-2600K with integrated HD3000 GPU. 
Very good results on fresh core!
BTW, standalone mesen is a little bit faster, see CPU/Cores loading:
[mesen_i7-2600K.zip](https://github.com/SourMesen/Mesen/files/1615501/mesen_i7-2600K.zip)

**Comment by Tatsuya79** [comment] 2018-01-09 15:38
I was told compiling with 
LTO=true make
gives better perfs here with msys2 on win7 x64.
And indeed I got something like +10% vs the buildbot core.

**Comment by eugene-s-nesdev** [comment] 2018-01-09 15:52
RPi3+Lakka+buildbot mesen_libretro.so (armhf)
32.4 FPS on that scrolling test (240pee.nes demo by tepples)
Anyway, it's good result.

There is awesome cycle-accurate nestopia core available for Raspberry Pi and other low-powered devices, like smartphones.

**Comment by SourMesen** [comment] 2018-01-09 16:45
Thanks for the confirmation!
FYI, my fix also caused an issue where changing aspect ratio/region/overscan settings won't properly update (needs a restart of the core in-between) - I'll fix it sometime tonight.

Also, thanks for testing on the RPi3 - that's pretty much what I expected.  Between the very small L2 cache & low clock speed on the RPi3, it's slower than desktop CPUs from 15 years ago for a lot of things.  Boosting performance by ~100% would be a bit hard.  At the very least, I would need a RPi3 myself to be able to test how the performance varies based on code changes in environments with small CPU cache & comparatively slow memory.

Standalone Mesen being a bit faster is expected - the standalone splits the processing for the final picture into a 2nd thread, and is optimized by PGO (which gives a 10-20% perf boost).  The libretro port strips out some things (e.g debugger-related functions), but it's still a bit slower.

@Tatsuya79 
The buildbot's core is built with MSVC, so you might get a different result when building w/ msys2 (LTO does make a big difference, too).  When testing the buildbot's windows builds, everybody seemed to be getting better performance with the MSVC build compared to gcc/clang, so we decided to use MSVC for it.

**Comment by eugene-s-nesdev** [comment] 2018-01-13 21:30
Hi, Sour!
Can you set default keyboard config to the:

Z = "B"
X = "A"
A = "Turbo B"
S = "Turbo A"

This configuration are default for nestopia and fceumm cores.
quicknes uses it too (but without turbo)

**Comment by SourMesen** [comment] 2018-01-16 03:31
@eugene-s-nesdev  I understand that they're the default for other cores, but in terms of the "retropad" implementation that libretro is supposed to emulate, setting the NES' B and A buttons to the retropad's B and A button results in a very unnatural layout, whereas the current mapping (Y and B) makes it play like Mario on the SNES would by default.

I've seen a few people talking about this here and there, and a lot of them seemed to be saying that the default I currently set is better than using B/A. So, I'm not too sure which is best, really.
Can't you just remap the buttons on your end, though?

**Comment by SourMesen** [comment] 2018-02-07 00:00
I think most things in here have been taken care of?  So I'll close this for now - feel free to open up other issues if there's anything else missing.

(The only libretro issue I am aware of at the moment is retroachivements not working properly for some games that use work ram)

**Closed by SourMesen** 2018-02-07 00:00 UTC

**Comment by rzumer** [comment] 2018-08-20 13:12
With a controller the default mapping is still incorrect. With 4 face buttons the alignment is swapped such that B turbo is assigned to what I believe should be the A button (or vice versa?)
I can look into this in more detail if you cannot reproduce it.
