### ISSUE TITLE
Mesen recreates every file on every startup...

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#247] opened 2017-09-11 16:11 UTC
So this is a little hard to explain so bare with me here, whenever you run Mesen every file that's apart of Mesens install is recreated, "GoogleDrive" "Resources" "MesenCore.dll" "MesenDB.txt" "MesenUpdater", etc. This would be expected behavior if on first startup, but on every launch thereafter?

All emulators (as far as I know) just spit out a newly/updated settings.ini or whatever, maybe a log file too without having to recreate every file on every start. Can you maybe just supply a .zipped package with everything inside it ready to go, instead of a single Mesen.exe file that's going to do all this recreating?

**Comment by SourMesen** [comment] 2017-09-11 20:44
Yes, this is by design and needed for a variety of reasons (auto-updates, shipping as a single file that runs on 4 different platforms).  `All emulators (as far as I know)`, typically do not do either of these :)

I'm not sure I'm seeing an actual problem? If you are worried about a SSD's longevity, it's unlikely that ~5mb worth of data being written every time Mesen is opened will have any lasting impact (even if you were to launch it 50 times a day, that's only 90gb of writes in a year, and SSDs are designed to handle 100000+ gigabytes of writes).

**Comment by ImSpecial** [comment] 2017-09-11 22:21
Defragmentation even though small, and the way I do my backups, because it sees them as "new" files every time, it wants to re-sync them, it's rather annoying.

Also I'm on Windows, don't use Google Drive, and don't use your MesenUpdate.exe for auto-update checking, personally I would like to just delete these to trim install footprint.

**Comment by SourMesen** [comment] 2017-09-11 22:33
On Windows, Mesen fits inside of 15mb - I'd understand the argument in 1990 when HDs were ~40mb in size, or in 1995 when they were ~800mb, but we are in 2017.
While I understand you may not use every feature available (and much like I said to other people in another recent discussion), you can't expect me to produce a tailored version of Mesen for each individual's needs - I'm not getting paid for this.  

The most I can do for you is to replace the delete/rewrite logic by something that will check that the file is present & validate its integrity before attempting to write it to the disk (e.g if its there and matches the file needed, nothing will be done), which would solve your fragmentation & backup concerns.

**Comment by ImSpecial** [comment] 2017-09-11 23:00
> ...replace the delete/rewrite logic by something that will check....

That would pretty much solve all my grip here. But I still think people care about space, no I'm not hurting for it, but no one wants to have "extra" stuff on their system like ever, Linux guys don't want to be bombarded with Windows dependence if they aren't required to, or having 20 different language folders/files, not planning to read Chinese anytime soon, regardless if they are only 30~KBs in size, etc. But I also don't expect you to release several versions for each type of user like me.

**Comment by SourMesen** [comment] 2017-09-13 00:54
This is fixed by c6f77c8a3dd991ccf788d82336fd403cc63d7b66 - files will only get written to the disk if they don't match the file Mesen expects (which should only happen after an upgrade)

**Closed by SourMesen** 2017-09-13 00:54 UTC
