### ISSUE TITLE
I can't start recording video.

### ISSUE THREAD

**Issue by Vinyl666** [SourMesen/Mesen#281] opened 2017-12-21 16:00 UTC
Recording stoped before i started.

**Comment by Cibomatto2002** [comment] 2017-12-22 15:25
you have to start the game before you can record it.

**Comment by SourMesen** [comment] 2017-12-22 15:46
What OS are you running?  Which version of Mesen are you using?
Could you attach your settings.xml file (you can find it in Mesen's data folder, which you can open by going to Preferences and clicking "Open Mesen Folder")? It's possible an option you are using is causing the issue - I can't reproduce it on my end.

**Comment by liaodahao** [comment] 2017-12-27 04:35
I have the same problem. I can't record video when enabling a video filter. Recording stopped as soon as it started.
Windows10 64bit, Mesen 0.9.3

**Comment by SourMesen** [comment] 2017-12-27 05:16
Thanks - I was able to reproduce it, the bug occurs whenever a filter other than the NTSC filters is used.
The bug is already fixed in recent builds (it was fixed by fec2a2130b3783a88f3481c4fe676f2964895562), so the fix will be available in the next release.

**Closed by SourMesen** 2017-12-27 05:16 UTC
Labels: bug
