### ISSUE TITLE
Allow mouse to auto-hide in Fullscreen Mode

### ISSUE THREAD

**Issue by Apocalypse612** [SourMesen/Mesen#616] opened 2019-04-13 23:47 UTC
Title. I find it aggrivating that I have to always move the mouse to the corner of the screen when full-screening Mesen.

**Comment by SourMesen** [comment] 2019-04-27 00:04
Is this in exclusive fullscreen mode?  It should definitely be hidden in windowed/fullscreen window modes.
If it's exclusive fullscreen, it might be a bug (haven't checked, so can't tell how easy it would be to fix).  But in general, unless you have a very good reason to use exclusive fullscreen, I wouldn't recommend it. 

At the very least, some of the input lag testing I've done with it seems to show that directx adds a frame or 2 worth of graphics delay when in exclusive fullscreen (for reasons I do not know)

**Comment by SourMesen** [comment] 2019-11-15 00:01
@Apocalypse612  Any more information on this?  I can't reproduce the issue in either windowed fullscreen or exlusive fullscreen modes on my end.

**Comment by Apocalypse612** [comment] 2019-11-25 02:49
Really sorry for not responding to this sooner, I completely forgot, then lost power for several days. I always liked how quickly you responded to me.

Anyway, I have some more information on this. If you DO NOT move the mouse, and exit a emulator paused state, the mouse will not hide itself until you move the mouse. Each time you pause and unpause the emulator, this action presents itself.

Does that help?

**Comment by SourMesen** [comment] 2019-12-24 20:34
Thanks for the info!
This should be fixed as of 553b84371e210581c2da86aef526c6a5ee1ad116.

**Closed by SourMesen** 2019-12-24 20:34 UTC
Labels: bug
