### ISSUE TITLE
Slowdown when recording Movie with external program

### ISSUE THREAD

**Issue by Kebbbs** [SourMesen/Mesen#264] opened 2017-10-11 23:31 UTC
When I attempt to record a Movie with an external program (OBS 20.0.1, in this case), I experience some slowdown. This does not occur when recording live gameplay, only during Movie playback. I've attached a video showcasing the issue. The footage begins with a recording of live gameplay, then switches to Movie playback at about 1:50. I'd be happy to provide more video if necessary.

https://youtu.be/t4i8TlCT5l8

**Comment by SourMesen** [comment] 2017-10-12 00:09
I tried the old version of OBS I happened to have installed (0.657) and also tried 20.0.1, but both seem to record without any slowdowns on my end.  Code-wise, there is very little reason why playing a movie would cause slowdowns whereas normal gameplay wouldn't, too. Have you checked your CPU usage and Mesen's CPU usage during recording? Does Mesen's CPU usage change between recording live gameplay vs recording a movie?

Generally speaking, if you're only trying to record gameplay (and not stream), it would probably be simpler to use Mesen's built-in avi recording feature (unless there is a reason you cannot do so).  This will record the video at the NES' native frame rate (60.1) and avoid dropped frames in the video file (which occur every ~10 seconds when recording at 60 FPS). Also, using the built-in avi recorder, you can record with no speed limit (e.g at 200-300fps) and the result will still be a normal 60.1 fps video with normal video & sound, so this can actually save some time if you're trying to make a video of a movie.

**Comment by Kebbbs** [comment] 2017-10-12 01:23
I have checked the CPU usage and while there is a slight uptick, there's not nearly enough to explain why this might be happening.  Mesen itself maxes out at maybe 15%, while OBS goes up to 20% or 25%.

After watching the CPU usage a bit more carefully, I've noted that if I begin playing the movie immediately after opening the program, I'll get about 30 seconds of clean playback, accompanied by a slight increase in CPU usage (jumping from 11-ish% to 15-ish%). But once that time is up, Mesen will begin slowing down again, with the CPU usage dropping as well. This appears to happen at the same spot in the recording every time.

As for the built-in recording feature, I've experimented with it before with mixed results, though playing with it now seems to produce a clean replay. I'm trying to record at 1080p and a 4:3 aspect ratio, but the recorder only seems to record at the native resolution and a "pixel perfect" aspect ratio. I can't find any settings to adjust it either. I'll cop to being pretty green at video production, so I'll play around with some of my software to see if I can upscale it without any issues, but I'd highly prefer to lighten the post-production load by grabbing the gameplay at the resolution I want.

Thank you for your fast reply!

**Comment by SourMesen** [comment] 2017-10-12 03:52
Without being able to reproduce it on my end, it's a bit hard to fix. For all I know, it could potentially be OBS' fault (e.g whatever way it uses to record the video/audio might be interfering).  Playing a .mmo file is essentially the same as just playing the game, except it reads the input from the .mmo file in memory instead of the keyboard/gamepad - performance-wise, it's identical.

I'm in the middle of rewriting pretty much everything input-related, including movies, though, so maybe those changes will somehow fix your problem (will be a few weeks at least before this is done, though).

The video recorder records the emulator's output (including filters), but as you said, it excludes scaling (and also bilinear filtering if it is enabled).  This is because both of these are done in hardware by DirectX, whereas the rest is done in software (and only the software portion of the rendering is recorded).
You should be able to re-encode/scale videos pretty easily using ffmpeg if you need to, though. (e.g from a quick google search, something like this: `ffmpeg -i input.avi scale=1440:1080 output.avi`

**Comment by SourMesen** [comment] 2017-12-29 23:14
I have not done anything to fix this, but it would be nice if you could check and see if version 0.9.4 still has the same behavior when recording with OBS

**Comment by SourMesen** [comment] 2018-02-07 01:08
Closing this for now, since I can't reproduce this on my end.

**Closed by SourMesen** 2018-02-07 01:08 UTC
Labels: cannot reproduce
