### ISSUE TITLE
Random Mesen Emulator Crashes

### ISSUE THREAD

**Issue by BaconIsDelicious17** [SourMesen/Mesen#229] opened 2017-09-01 23:41 UTC
Hello I just wanted to report a bug with the emulator, I recently started using the Mesen Emulator about 6 days ago and the Emulator has already crashed every time I have used it. 1st time was while playing Mega Man 2, 2nd time was while playing Mega Man 3 and the 3rd time was while playing I'm Kid Dracula. All crashes/ stops responding happened around the 2nd hour of playing the games. Thank You and have a nice day.

**Comment by SourMesen** [comment] 2017-09-01 23:51
Thanks for the report.
What OS are you using? Is it a 32-bit or 64-bit OS?
What version of Mesen are you using? 0.9.1?
Were you using any specific feature or doing something specific when it crashed? e.g loading a savestate, rewinding, etc.

When a program crashes, Windows usually creates a "crash dump" and puts it into this folder:
C:\Users\<your profile name>\AppData\Local\CrashDumps
Can you see if you can see files named "Mesen.exe.<number>.dmp" in that folder?
If you find some, could you zip them (they are a lot smaller once zipped) and attach them to this bug report?

**Comment by OrangeChicken16** [comment] 2017-09-02 02:29
I am using Windows 7 Home 64 Bit and Mesen 0.9.1. I found 2 dmp files. I wanted to mention that I closed the Emulator using Task Manager so I don't know if I gave my computer the opportunity to log the information about the errors, but I will try playing a game again with the Emulator to see if the error happens again and I will not force it to close using Task Manager and then I will send you a newer dmp file.

[MesenBR.zip](https://github.com/SourMesen/Mesen/files/1271843/MesenBR.zip)

**Comment by SourMesen** [comment] 2017-09-02 05:09
Thanks for the info - I was able to open the dmp files, but because I forgot to save some files that get created when I made the builds, I can't really get too much info from them.
If you can, try to reproduce the crashes using this build instead: https://www.mesen.ca/MesenTest.zip
I kept the files I need to debug the dmp file for this specific build, so if you get the crash with it, I should be able to get a bit more information about why/where the code is crashing

**Comment by OrangeChicken16** [comment] 2017-09-03 07:42
Is this AppHang WER File useful?
[AppHang_Mesen.exe_d9ce1aad60ff968afd2d4042843b01cd6ca533b_176cd25d.zip](https://github.com/SourMesen/Mesen/files/1272796/AppHang_Mesen.exe_d9ce1aad60ff968afd2d4042843b01cd6ca533b_176cd25d.zip)

**Comment by SourMesen** [comment] 2017-09-03 12:33
Unfortunately, not really. But, if the problem is that Mesen is hanging (rather than crashing), then it might hopefully be easier to figure out the source.
You can manually force Windows to create a .dmp file of a process at any time - just right-click on any process in the task manager and click the "Create dump file" option.  It will create a .dmp file on your disk and tell you where it was saved.
When Mesen freezes, open up task manager and take a dump file while it's still frozen - that should let me see where exactly the freeze occurs.

**Comment by OrangeChicken16** [comment] 2017-09-04 05:10
Thank You for the information. I will have to send you the file by e-mail because of the 10 MB limit

**Comment by Cibomatto2002** [comment] 2017-09-06 00:30
You can upload it to here.

https://uploadfiles.io/

**Comment by SourMesen** [comment] 2017-09-17 18:04
For your information, I've checked the latest dump file you've sent me as well, but still cannot find anything wrong with the emulator's state in the dump file.
I'll check again once I have some time, but I can't make any promises since I'm unable to reproduce the issue on my end so far.

If you notice any pattern in how/when the emulator freezes (e.g if it freezes after a specific amount of time, or after changing a specific setting, etc.), please let me know.

**Comment by SourMesen** [comment] 2017-12-29 23:17
I haven't done anything specifically to fix this, but you might want to try version 0.9.4 to see if it solves the problem you were experiencing.

**Comment by SigmaVirus** [comment] 2017-12-31 10:00
I can test this out later tonight because we are going away for a couple of hours before new years eve at midnight so if I leave Mesen 0.9.4 open with Rockman 2 - Dr. Wily no Nazo running I could easily see if the game have hanged or crashed when I get back home.

If the game is still running after 4 hours for example we can say everything is good to go!

**Comment by SigmaVirus** [comment] 2017-12-31 20:55
Happy new year everyone!

@SourMesen 

It's 21:54 CET and it's soon a new year and I bring good news with my final GitHub post for 2017.

Approximately 15:03 CET I started a Mesen 0.9.4 test run with Rockman 2 - Dr. Wily no Nazo and I must say it still ran when I got home from a party 15 minutes ago so for over 5 hours I left Mega Man standing on Air Mans stage on the place with robotic worms constantly coming out from the ground and when I got home I completed the stage successfully.

So whatever problem there might have been here with hanging and crashing after 2 hours as @OrangeChicken16 had originally reported is most likely gone now with 0.9.4.

I hope this report helped you and with this I bid you farewell until 2018!

**Comment by SourMesen** [comment] 2018-01-01 14:28
Thanks for testing, always good to see how it works out on someone else's computer.
This may be an issue specific to OrangeChicken16's particular setup, though, so if possible I'd like to know whether it is fixed on their environment or not.

**Comment by SigmaVirus** [comment] 2018-01-01 16:55
Glad to be of assistance!

Mesen is rock solid on my end and with FirebrandX's palettes, NTSC filter enabled and a Famicom lookalike USB controller from iBuffalo it's like I'm playing my Famicom and Famicom Disk System games on my Famicom!

**Comment by OrangeChicken16** [comment] 2018-01-26 10:37
@SourMesen Hello, sorry for not responding sooner, I just read the messages today. I tried out the emulator today and Mesen 0.9.4 still crashes/hangs on my computer. The game suddenly stopped working twice and both times it was within a half hour of playtime. I will send you the dmp files. I have a question, is there any specific program requirements necessary to run Mesen Emulator correctly? For example any specific Microsoft Visual C++? or Microsoft .NET Framework? Thank you for your time and have a nice day.

**Comment by SourMesen** [comment] 2018-08-28 00:26
@BaconIsDelicious17 
Hey, sorry for the super late reply.  0.9.6 was released a few weeks ago and does contain a fair number of changes in the code that could potentially have an impact on your issue, if possible, could you give it a try once you get a chance?

I checked the last dump files you sent me a while ago, but unfortunately I wasn't able to figure out the cause from them, either.

As for running Mesen, the only requirements on Windows are DirectX 11 and .NET 4.5 - essentially, if the program starts, you're fine, missing dependencies would not cause this kind of behavior.

**Closed** 2018-12-03 07:04 UTC
Labels: bug, cannot reproduce

**Comment by stealthAngel** [comment] 2019-07-12 19:18
To solve this issue you need to run mesen as administrator.

**Comment by jackwilsdon** [comment] 2019-07-12 19:57
That's not a good solution @stealthAngel — an emulator shouldn't really require administrative privileges and by running it as administrator you're most likely just patching over some form of file ownership / permissions problem on your syste.

**Comment by stealthAngel** [comment] 2019-07-13 23:44
@jackwilsdon I'm pointing out what works.
