### ISSUE TITLE
Crash on Arkanoid+Four Score

### ISSUE THREAD

**Issue by pinobatch** [SourMesen/Mesen#236] opened 2017-09-06 01:09 UTC
I am using Mesen 0.9.2 in Mono in Debian 9. If I run [allpads-r9](https://forums.nesdev.com/viewtopic.php?p=184716#p184716), set player 2 to Arkanoid Controller, and turn on Four Score, I get an unhandled null reference exception that I don't know how to copy and paste. At that point, the main window of Mesen becomes unresponsive to anything but `kill -9 pid_of_mesen`. The normal terminate signals (SIGINT and SIGTERM) do not kill it.

The expected behavior is that D3/D4 controllers (Zapper, Arkanoid Controller, and eventually the Power Pad) turn into None because that's what the Four Score sees them as.

What steps should I take to help you troubleshoot this null reference exception?

**Comment by SourMesen** [comment] 2017-09-06 04:29
Thanks for the report - I was able to reproduce the bug in my Ubuntu VM.
Looks like it's one of those cases where Mono's WinForms behaves slightly differently from MS' implementation - it should be fixed by 4c72d8edc0054dc60ac43d8c3118f382199c0560

**Closed by SourMesen** 2017-09-06 04:29 UTC
