### ISSUE TITLE
Graphical glitch in Super Mario Bros 

### ISSUE THREAD

**Issue by kurayami6** [SourMesen/Mesen#762] opened 2020-02-02 09:45 UTC
Playing a zipped rom of Super Mario Bros. + Duck Hunt + World Class Track Meet (USA) (Rev 1) in Mesen version 0.9.9 I got a few graphical glitches.

![Capture](https://user-images.githubusercontent.com/31968468/73606294-e5efe200-45fc-11ea-90da-5144e4521d2e.PNG)

![Capture2](https://user-images.githubusercontent.com/31968468/73606297-eb4d2c80-45fc-11ea-92be-cad7b9920b44.PNG)

**Comment by SourMesen** [comment] 2020-02-02 14:13
Thanks for the report.

I can't reproduce this at all on my end - can you?

**Comment by kurayami6** [comment] 2020-02-02 14:32
No I can't. I have no idea what caused it or how to make it happen again.

**Comment by SourMesen** [comment] 2020-02-12 04:12
Based on the way it looks in the screenshots, it's fairly likely to be a rare bug in the game itself (maybe specific to this particular cart?)  It's fairly unlikely to be an emulation bug, but I don't really have any way of confirming either possibility - closing this one for now.

If someone can finds a way to reproduce it consistently and proves this never happens on hardware, I can take a closer look at it.

**Closed by SourMesen** 2020-02-12 04:12 UTC
