### ISSUE TITLE
Debugger's Assembler Can't Revert Code

### ISSUE THREAD

**Issue by torridgristle** [SourMesen/Mesen#449] opened 2018-08-05 18:17 UTC
I set a breakpoint to show me what's reading an address and changed the code from CMP $34 to LDA $34, and now I can't apply the changes made when I replace LDA $34 with CMP $34 because the "New code matches original code". I don't know how to revert it.

**Comment by SourMesen** [comment] 2018-08-05 18:45
I can't reproduce this - I can only assume the code has actually already been reverted by some other means (e.g File->Revert all PRG/CHR changes, or Ctrl-Z anywhere in the code window, or right-click->Undo PRG/CHR edit).

If you close and reopen the debugger window and check the code, does it says CMP or LDA?  I would assume it says CMP if the assembler isn't letting you write CMP.

**Comment by torridgristle** [comment] 2018-08-05 20:31
I can't seem to make it happen again. If I use Ctrl-Z in the memory editor then the code updates in the debugger so I don't think I did that, and I remember seeing the Revert all PRG/CHR changes option and thinking something along the lines of I ain't gonna need that right now so I definitely didn't do that.

I ain't sure how this happened but it was definitely actually reverted earlier. Trying to redo it showed a big change in behavior when it's LDA instead of CMP and it was behaving as though it was CMP when I couldn't change the code to CMP in the debugger. So thankfully it ain't an issue with applying code, it just didn't update in the debugger when it somehow reverted, though the debugger knew it was the current code despite displaying LDA.

**Comment by ansstuff** [comment] 2019-11-22 00:38
I believe that's not a bug but a confusion caused by Debugger not displaying memory changes made in Memory Editor. For me that was definitely the case when trying to change opcodes similarly.

There needs to be a way to always keep Debugger and Memory tools up-to-date (without unnecessary overhead though), for example, force update every time Debugger window gains focus.

**Comment by SourMesen** [comment] 2020-02-01 16:22
As of 19b93dc343f64007777e24f6e3075ca0475759c5, the debugger window will update the disassembly when it gains focus.  There were also a couple of scenarios where editing ram would not update the disassembly, which have been fixed in 0.9.8, so hopefully this is fixed.

**Closed by SourMesen** 2020-02-01 16:22 UTC
Labels: bug, cannot reproduce
