### ISSUE TITLE
8-BIT ADV STEINS;GATE Shaking text box

### ISSUE THREAD

**Issue by AlterShiki** [SourMesen/Mesen#681] opened 2019-10-11 01:08 UTC
This is not supposed to happen although I can't confirm that it does not happen on real hardware as the game is originally being emulated on the Nintendo Switch version, changing the region in the settings seems to have an impact on the text box with Dendy being the least shaky, this does not occur on Nestopia and the text box isn't shaky however changing the region to PAL on Nestopia seems to affect the textbox as well but I can't say its related to the problem at all.

here's a clip of the shaky textbox in action: https://i.imgur.com/dl82EyJ.mp4

tested on Mesen 0.9.8

**Comment by SourMesen** [comment] 2019-10-11 03:19
Thanks for the report!

I've identified a change between 0.9.5 and 0.9.6 that causes it to happen.  But here's the catch, as far as I understand, the behavior I implemented in that change is correct and matches real hardware (and doesn't cause problems in any other game that I am aware of.)  It's not impossible that it could be wrong, though.

Like you said, the game was developed with an emulator in mind, and it's very likely it was never properly tested on a real MMC3 board.  Ideally, would need someone to test the game on a real MMC3 board to be certain.  A powerpak/everdrive *might* also be good enough to test, but I'd be a little wary of those since they also emulate the MMC3 chip.

**Comment by dragon2snow** [comment] 2019-10-11 05:15
mmc3a

**Comment by SourMesen** [comment] 2019-10-12 15:01
Alright, after some investigating and testing, it does look like this was caused by a couple of bugs that only had an impact in very specific circumstances. These should be fixed by 5b6b57be72c6bec0b467992a2635873d7bc121dd and 30c2c8d3bf6410e249a72437ea453c5bc59f94d6.

Note that this does still cause the dialog to shake as soon as the music starts (and there's a very noticeable red/pink line that shows up in the middle of the screen, too).  But as far as I can tell, these are also visible in all other accurate emulators (and appear when playing on the EverDrive, too.)

Thanks again for the report!

**Closed by SourMesen** 2019-10-12 15:01 UTC
Labels: bug
