### ISSUE TITLE
Guardian Legend Overclocking Issue

### ISSUE THREAD

**Issue by Koh1fds** [SourMesen/Mesen#152] opened 2017-04-29 17:49 UTC
At first it looks fine. You have to use extra scanlines after NMI to prevent shaking of information bar. But after you beat some particular mini bosses - information bar starts to shaking when screen transition happens. You can fix it by opening item menu. Here is video demonstration of it: https://youtu.be/lXqvdgIgNEw
And here is Save State just before that particular mini boss fight
http://s000.tinyupload.com/index.php?file_id=01124711092018547462
Also i use 480 extra scanlines. And also this game works perfectly in fceux with 480 Post render scanlines. Also i use japanese version of the game (Guardic Gaiden)

**Comment by SourMesen** [comment] 2017-04-29 18:26
Overclocking in general can break just about anything in any game.  The fact that it works in FCEUX doesn't really mean it's supposed to work in general - any timing differences between FCEUX and Mesen could cause differences in the behavior here (and it looks like FCEUX's overclocking is only available with the its old (and very inaccurate) PPU implementation, too.)

Is there any reason you need to use 480 extra lines? That's huge - you're making the time spent in NMI 25 times longer than normal.  Have you tried smaller values?  Either way, I don't think this is something I can fix, though.

**Comment by Koh1fds** [comment] 2017-04-29 18:50
No particular reason for 480 extra scanlines. After overclock by adding extra scanlines was first introduced in fceux i did testing how many extra scanlines you need to completely remove lag and i think it was between 200-300 extra scanlines. Then i was thinking that 480 extra scanlines gives like x3 power to cpu (at that time i didn't even know about vblank). So i stuck with 480, because i won't to test every game to know exact number you need to completely remove lag. Pretty sad to hear. I was thinking about mesen like it's pretty accurate emulator with overclock. It was like huge jump after fceux. It will be more sad if there is more games glitches with overclock in mesen, because it will be trow back to fceux again.

**Comment by SourMesen** [comment] 2017-04-29 19:25
Overclocking, in any emulator, throws "accuracy" out of the window - it changes the most basic rules of the PPU's timing vs the CPU, and can break just about anything. Overclocking is pretty much like running a NTSC game on a PAL console - it might work, or it might cause problems.  Problems with overclocking are impossible to predict, and there is no way to fix them other than trying alternative overclock settings.  

With 480 extra lines, you are running the CPU 3 times faster than it is supposed to be.  As far as I can tell, the game works fine up to about 430 extra lines.  Honestly, even 430 lines seems overkill to me.  For example, in Megaman 1, with no overclock I am getting up to 30 lag frames per second.  With as little as 30-40 extra lines, it drops down to 1 "lag frame" every ~10 seconds (so 300 times less), which makes any lag impossible to notice.

**Comment by Koh1fds** [comment] 2017-04-29 19:28
Try really laggy game like Contra Force. You get a lot of lag frames even with 200 extra nscanlines

**Comment by SourMesen** [comment] 2017-04-29 20:14
There was a difference between FCEUX and Mesen's implementation which caused Mesen to disable overclocking on some frames in Contra Force because of the DMC channel while FCEUX did not - I changed it (aab1c25a2b0c431bcdcea9da26abe59ced3c2fe0).

I'm not sure what you want me to say - there is nothing else that I can fix. The overclocking in FCEUX and Mesen (with regards to extra lines before/after NMI) works the exact same way. If a game happens to glitch due to this in Mesen and FCEUX, then that's because of the different timings between both emulators.  It's also possible that some games might glitch in FCEUX, but not Mesen, there's no way to know.

**Comment by Koh1fds** [comment] 2017-04-29 20:28
>I'm not sure what you want me to say
Everything i want to have like an emulator with same level of sound quality as Mesen, but without like glitches while you using an overclock. I mean it was a hope that Mesen would be like that. That's my ultimate dream. Like have everything. Overclock, more that 8 extra sprites per scanlines, no glitches, no lag, perfect sound. Everything. But that's ok if Mesen have like different aim. Nevermind.
I think i can tell :D Here is a compatibility list for overclock:
https://docs.google.com/spreadsheets/d/1exirXMWNp20OWdgRjosIrRh38-cpXLouga_P6A-jHp0/edit#gid=0
And also i can say for myself that i played around 250 games from beginning to the end with 999 extra scanlines looking extremely closely for slightest issue with overclock in fceux. I say that there is no issue at all with any of those games in current version. And with mesen it was like the first game that i tested and i get huge thing like shaking bar.

**Comment by SourMesen** [comment] 2017-04-29 21:25
After searching some more, I did find a difference in FCEUX's and Mesen's overclocking and it does seem to be the cause of the issue (it's related to how FCEUX overclocks the APU).  I did a quick test and it looks like it fixes Guardic Gaiden, I don't have the time right now, but should be able to fix this later today or tomorrow.

**Comment by SourMesen** [comment] 2017-04-30 01:41
This should be fixed by cf8c98f3840f6f1459a90218a251b03c5446b701.
Please give it a shot in the next release and let me know if you find any other issues.

**Closed by SourMesen** 2017-04-30 01:41 UTC
