### ISSUE TITLE
Mesen freezes/locks up when loading .dbg labels

### ISSUE THREAD

**Issue by gauauu** [SourMesen/Mesen#273] opened 2017-11-10 05:02 UTC
I created a .dbg file using ld65's --dbgfile option.

When I open the mesen debugger, and file -> workspace -> import labels, and load the file, Mesen instantly locks up.  Processor usage of mesen jumps up to around 50% cpu.

The same thing happens when I set it up to auto-load dbg files. 

This happens in linux mint running mesen in mono.

I can send the rom and dbg file if that would be helpful.

Thanks!

**Comment by SourMesen** [comment] 2017-11-10 12:17
Just gave it a quick try under Ubuntu with a relatively big .dbg file (~3000 labels) and it didn't freeze up, so having your rom & .dbg would hopefully help me reproduce this (feel free to e-mail them if you don't want to make them public)

**Comment by gauauu** [comment] 2017-11-10 15:22
Thanks for checking. I PM'd you the rom and .dbg file on the nesdev forum.

**Comment by SourMesen** [comment] 2017-11-11 00:29
Thanks - I was able to reproduce the freeze.  It was a Linux-specific bug caused by using a backslash as a directory separator (invalid in Linux), which was causing an infinite loop in the code that loads the .dbg files (only when one or more source files cannot not be found in the .dbg's folder).  This is fixed by 8d8b74f77f716441d493d74a8e70146e4473e86b.  If you are building Mesen yourself, you should be able to build from the latest commit and use that (it contains a pretty large amount of debugger-related fixes compared to 0.9.3)

**Closed by SourMesen** 2017-11-11 00:29 UTC
