### ISSUE TITLE
Erroneous libretro memory layout

### ISSUE THREAD

**Issue by rzumer** [SourMesen/Mesen#642] opened 2019-07-10 04:49 UTC
It seems that the SRAM memory region is not configured correctly for Mesen in libretro. Please see https://github.com/meleu/RetroArch-problematic-cheevos/issues/42 for information. It is rather consistent to reproduce. After configuring achievements in RetroArch and launching the title, I was able to trigger one wrong detection on boot and another after the introduction battle.

This likely points to an error in memory descriptors, or the data being passed via `retro_get_memory_data()`.

The reference memory map is defined [here](https://github.com/RetroAchievements/RAIntegration/blob/master/src/data/ConsoleContext.cpp#L292).

**Comment by rzumer** [comment] 2019-07-10 05:18
I took a look at the memory descriptors and they seem fine to me. I wonder if there is something different with how Mesen manages save RAM compared to other emulators. It seems like the expected layout should match that of FCEUX/FCEUmm.

**Comment by SourMesen** [comment] 2019-07-12 21:30
Thanks for the report.  Essentially, it looks like the save ram mappings aren't being setup properly.  At boot time, the code goes through the available types of ram and maps them, but at boot, the save ram is not mapped into CPU memory for the MMC3 - the game has to write to a register to enable save ram.

Since the mapper doesn't boot up with its save ram enabled, the core doesn't know at what address the save ram is (0x6000) and so it doesn't map it at all (not sure why this results in achievements firing off for no reason, though!).

I'll have to see what I can do (that doesn't involve sending the mappings to the frontend every frame).

**Comment by rzumer** [comment] 2019-07-12 21:50
That makes sense, thank you for checking.

**Comment by rzumer** [comment] 2019-07-27 15:38
> At boot time, the code goes through the available types of ram and maps them, but at boot, the save ram is not mapped into CPU memory for the MMC3 - the game has to write to a register to enable save ram

I should point out that unless I misunderstood your comment, if save RAM is mapped in the CPU memory space by reference, but the backing data is allocated at boot time, it should be possible to point to the same data buffer in the libretro memory descriptors, regardless of whether it is enabled in the CPU space.

**Comment by SourMesen** [comment] 2019-07-27 17:43
Yes, they're mapped by a reference and the actual memory array is separate.
The problem is that the retroachievement/libretro API expect me to tell them *where* the SRAM is (e.g 0x6000-0x7FFF), but I can't know that without actually letting the game run, for some mappers. The API isn't great when it comes to systems where the SRAM can be in different places based on the cartridge and also be bankswitched (some MMC5 games have 32kb of bankswitched SRAM).

There are definitely hacky solutions that would work for most scenarios, I was just hoping to find one that one that would properly set the mappings in all scenarios.  Haven't really had the chance to take another look at this since my first reply, my free time has mostly been spent on the SNES emulator lately.

**Comment by soredake** [comment] 2020-04-05 14:14
Any progress on this?

**Comment by Sanaki** [comment] 2020-06-04 21:22
Could this same method be used to fix Mesen's SRAM issue?
libretro/SameBoy@84d9545

**Comment by SourMesen** [comment] 2020-06-23 18:54
This should be fixed (or at least substantially better) as of commit 3154f19467aa606493591687070e1bdd6fd867ab
Let me know if there are any other problematic games.

**Closed by SourMesen** 2020-06-23 18:54 UTC
Labels: bug, libretro
