### ISSUE TITLE
Input lag could be reduced by 1 frame

### ISSUE THREAD

**Issue by Tatsuya79** [SourMesen/Mesen#298] opened 2018-01-05 21:16 UTC
Tested in libretro and windows stand-alone with smb1:
Mario jumps in 3 frames when you do "next frame" (it's K in Retroarch).

Other cores like Nestopia or Fceumm react in 2 frames.

Tested on Win7 x64.

**Comment by SourMesen** [comment] 2018-01-05 22:28
Thanks - I think I have an idea what the problem is.
Could I ask you to check 0.9.3 and see if the same extra frame is there? I have a feeling this might be new to the input rework I did in 0.9.4.

**Comment by Tatsuya79** [comment] 2018-01-05 22:49
3 frames in 0.9.3 and 0.9.2, no difference.
Perhaps the polling is happening too late after the frame rendered?

**Comment by SourMesen** [comment] 2018-01-05 22:54
Weird, I thought 0.9.3 would be different - but maybe something else is causing it to be the same.
I didn't check this in detail yet, but I think it's doing this:
Scanline 240: Read input
Scanline 241: Send previous frame to video card, sleep until we're ready for the next frame (~15ms)
Scanline 246: SMB reads the input, based on what we polled on scanline 240, ~15ms ago, which is obviously not a good thing.

0.9.3 should have polled the input at scanline 246, when the game asked (it didn't have per-frame input), so I would have expected it to be better on latency in this case.  I'll try to build you a libretro core with a potential when I get a chance

**Comment by SourMesen** [comment] 2018-01-07 15:32
Thanks for the report - this should be fixed by a0a6d89416ed68dc5ac3be74a01c02430e7f2197

**Closed by SourMesen** 2018-01-07 15:32 UTC

**Comment by Tatsuya79** [comment] 2018-01-07 20:17
Thanks! got 2 frames of reaction now in RA. 👍
